2024-12-25 17:32:21 - Logger - INFO: ===================================테스트 케이스 실행 시작: TestCase01===================================
2024-12-25 17:32:21 - Logger - INFO: 마이메뉴 아이콘('css selector', 'ul.header-menu-list-1 > li:last-child a.icon-myInfo-1')(을)를 찾았습니다.
2024-12-25 17:32:22 - Logger - INFO: 마이메뉴 아이콘 <selenium.webdriver.remote.webelement.WebElement (session="d3c738eb60a8f6e68d406aa17f1d276c", element="f.56FAC78465B521F37F76B190AEB475E8.d.61F7E5F15C9708D4CF14BBBFC712EAD3.e.942")>로 마우스를 이동했습니다.
2024-12-25 17:32:22 - Logger - INFO: 마이메뉴 활성화 조건('css selector', 'a.icon-myInfo-1.is-active, div.myInfo-list.is-show')들을 2개 찾았습니다.
2024-12-25 17:32:22 - Logger - INFO: 마이메뉴 마우스오버시 드롭메뉴 활성화 성공
2024-12-25 17:32:22 - Logger - INFO: 메인로그인 버튼('css selector', "a.btn-my.c-btn-solid-1-m[data-gtm-click-text='로그인']")(을)를 찾았습니다.
2024-12-25 17:32:23 - Logger - INFO: 메인로그인 버튼{'tag_name': 'a', 'id': '_uid_179', 'class': 'btn-my c-btn-solid-1-m'}(을)를 클릭 성공하였습니다.
2024-12-25 17:32:23 - Logger - INFO: 클릭 요소안의 URL: https://www.lguplus.com/login
2024-12-25 17:32:23 - Logger - INFO: 로그인페이지 리다이렉션 성공 URL: https://www.lguplus.com/login
2024-12-25 17:32:23 - Logger - INFO: U+ID 버튼('css selector', 'section.new-mem-section ul.iconLoginList li:nth-of-type(4) button')(이)가 클릭 가능한 상태입니다. 
2024-12-25 17:32:23 - Logger - INFO: U+ID 버튼{'tag_name': 'button', 'id': '_uid_192', 'class': ''}(을)를 클릭 성공하였습니다.
2024-12-25 17:32:24 - Logger - INFO: U+ID 로그인페이지 리다이렉션 확인 URL: https://www.lguplus.com/login/onid-login
2024-12-25 17:32:24 - Logger - INFO: 로그인 폼('css selector', 'div.nm-loginPage')(을)를 찾았습니다.
2024-12-25 17:32:24 - Logger - INFO: 아이디 입력창('css selector', '#username-1-6')(을)를 찾았습니다.
2024-12-25 17:32:24 - Logger - INFO: 아이디 입력창('css selector', '#username-1-6')에 'tmk3602@naver.com' 텍스트를 입력하였습니다.
2024-12-25 17:32:24 - Logger - INFO: 비밀번호 입력창('css selector', '#password-1')(을)를 찾았습니다.
2024-12-25 17:32:24 - Logger - INFO: 비밀번호 입력창('css selector', '#password-1')에 'rlaxorals1!' 텍스트를 입력하였습니다.
2024-12-25 17:32:24 - Logger - INFO: U+ID로그인 버튼('css selector', 'button.c-btn-solid-1.nm-login-btn')(을)를 찾았습니다.
2024-12-25 17:32:24 - Logger - INFO: U+ID로그인 버튼{'tag_name': 'button', 'id': '_uid_199', 'class': 'c-btn-solid-1 nm-login-btn'}(을)를 클릭 성공하였습니다.
2024-12-25 17:32:27 - Logger - INFO: 메인페이지 리다이렉션 확인 URL: https://www.lguplus.com/
2024-12-25 17:32:27 - Logger - INFO: 마이메뉴 아이콘('css selector', 'ul.header-menu-list-1 > li:last-child a.icon-myInfo-1')(을)를 찾았습니다.
2024-12-25 17:32:29 - Logger - INFO: 마이메뉴 아이콘 <selenium.webdriver.remote.webelement.WebElement (session="d3c738eb60a8f6e68d406aa17f1d276c", element="f.56FAC78465B521F37F76B190AEB475E8.d.61F7E5F15C9708D4CF14BBBFC712EAD3.e.942")>로 마우스를 이동했습니다.
2024-12-25 17:32:29 - Logger - INFO: 마이메뉴 정보 텍스트('css selector', '.login-info-txt')(을)를 찾았습니다.
2024-12-25 17:32:29 - Logger - INFO: 마이메뉴 정보 텍스트('css selector', '.login-info-txt')에서 텍스트 '김*민님 반갑습니다.'를 가져왔습니다.
2024-12-25 17:32:29 - Logger - INFO: ===================================테스트 케이스 실행 완료: TestCase01===================================
2024-12-25 17:33:01 - Logger - INFO: ===================================테스트 케이스 실행 시작: TestCase02===================================
2024-12-25 17:33:01 - Logger - INFO: 메인페이지gnb_section 영역('css selector', 'header > div.header-gnb-wrap')(이)가 화면에 보입니다.
2024-12-25 17:33:01 - Logger - INFO: 메인페이지kv_section 영역('css selector', 'div.swiper-wrapper')(이)가 화면에 보입니다.
2024-12-25 17:33:01 - Logger - INFO: 메인페이지kv_section_img 영역('css selector', 'div.swiper-wrapper .swiper-slide img')(이)가 화면에 보입니다.
2024-12-25 17:33:02 - Logger - INFO: 메인페이지benefit_section 영역('css selector', 'div.benefits-section')(이)가 화면에 보입니다.
2024-12-25 17:33:02 - Logger - INFO: 메인페이지device_section 영역('css selector', 'div.device-section')(이)가 화면에 보입니다.
2024-12-25 17:33:02 - Logger - INFO: 메인페이지blurb_section 영역('css selector', 'div.blurb-section')(이)가 화면에 보입니다.
2024-12-25 17:33:02 - Logger - INFO: 메인페이지payment_section 영역('css selector', 'div.payment-section')(이)가 화면에 보입니다.
2024-12-25 17:33:02 - Logger - INFO: 메인페이지promotion_section 영역('css selector', 'div.promotion-section')(이)가 화면에 보입니다.
2024-12-25 17:33:02 - Logger - INFO: 메인페이지custom_section 영역('css selector', 'div.custom-section')(이)가 화면에 보입니다.
2024-12-25 17:33:02 - Logger - INFO: KV영역 이미지('css selector', 'div.swiper-wrapper .swiper-slide img')들을 6개 찾았습니다.
2024-12-25 17:33:02 - Logger - INFO: KV영역 이미지 1번째 src: https://image.lguplus.com/static/pc-contents/images/fcmm/cnts/imge/20241219-103656-562-OSz3Mzfs.png
2024-12-25 17:33:02 - Logger - INFO: KV영역 이미지 2번째 src: https://image.lguplus.com/static/pc-contents/images/fcmm/cnts/imge/20241219-103647-529-ngA0RkNo.png
2024-12-25 17:33:02 - Logger - INFO: KV영역 이미지 3번째 src: https://image.lguplus.com/static/pc-contents/images/fcmm/cnts/imge/20241105-041221-832-yXTUOHod.jpg
2024-12-25 17:33:02 - Logger - INFO: KV영역 이미지 4번째 src: https://image.lguplus.com/static/pc-contents/images/fcmm/cnts/imge/20241209-100305-833-W6w2NU0A.png
2024-12-25 17:33:02 - Logger - INFO: KV영역 이미지 5번째 src: https://image.lguplus.com/static/pc-contents/images/fcmm/cnts/imge/20241107-021224-522-9uDyNe17.png
2024-12-25 17:33:02 - Logger - INFO: KV영역 이미지 6번째 src: https://image.lguplus.com/static/pc-contents/images/fcmm/cnts/imge/20240910-053034-599-la1DxPPz.jpg
2024-12-25 17:33:02 - Logger - INFO: ===================================테스트 케이스 실행 완료: TestCase02===================================
2024-12-25 17:37:44 - Logger - INFO: ===================================테스트 케이스 실행 시작: TestCase03===================================
2024-12-25 17:37:44 - Logger - ERROR: 기기 추천 영역 테스트 실패: find_element() takes from 2 to 3 positional arguments but 4 were given
2024-12-25 17:37:44 - Logger - ERROR: Traceback (most recent call last):
  File "d:\test-rpa\pages\main.py", line 40, in execute
    device_section = find_element(self.driver, By.CSS_SELECTOR, self.locators['device_section'], f"기기 추천 영역")
                     ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: find_element() takes from 2 to 3 positional arguments but 4 were given

2024-12-25 17:37:44 - Logger - ERROR: 예상치 못한 예외 발생: TypeError
2024-12-25 17:37:44 - Logger - INFO: 스크린샷 저장 완료: d:\test-rpa\screenshots\TestCase03_기기추천영역테스트실패_20241225173744.png
2024-12-25 17:37:44 - Logger - ERROR: ===================================테스트 케이스 실행 실패: TestCase03 - find_element() takes from 2 to 3 positional arguments but 4 were given===================================
2024-12-25 17:38:16 - Logger - INFO: ===================================테스트 케이스 실행 시작: TestCase03===================================
2024-12-25 17:38:16 - Logger - ERROR: 기기 추천 영역div.device-section(을)를 찾지못했습니다.: WebDriver.find_element() takes from 1 to 3 positional arguments but 19 were given
2024-12-25 17:38:16 - Logger - ERROR: Traceback (most recent call last):
  File "d:\test-rpa\utils\custom_utils.py", line 237, in find_element
    element = WebDriverWait(driver, EXPLICIT_WAIT).until(
        EC.presence_of_element_located(locator)
    )
  File "C:\Users\kasun\AppData\Local\Programs\Python\Python313\Lib\site-packages\selenium\webdriver\support\wait.py", line 96, in until
    value = method(self._driver)
  File "C:\Users\kasun\AppData\Local\Programs\Python\Python313\Lib\site-packages\selenium\webdriver\support\expected_conditions.py", line 84, in _predicate
    return driver.find_element(*locator)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
TypeError: WebDriver.find_element() takes from 1 to 3 positional arguments but 19 were given

2024-12-25 17:38:16 - Logger - ERROR: 예상치 못한 예외 발생: TypeError
2024-12-25 17:38:16 - Logger - INFO: 스크린샷 저장 완료: d:\test-rpa\screenshots\NoneType_기기추천영역div.device-section(을)를찾지못했습니다._20241225173816.png
2024-12-25 17:38:16 - Logger - ERROR: 기기 추천 영역 None로 마우스를 이동하지 못했습니다.: move_to requires a WebElement
2024-12-25 17:38:16 - Logger - ERROR: Traceback (most recent call last):
  File "d:\test-rpa\utils\custom_utils.py", line 162, in move_to_element
    actions.move_to_element(element).perform()
    ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\kasun\AppData\Local\Programs\Python\Python313\Lib\site-packages\selenium\webdriver\common\action_chains.py", line 253, in move_to_element
    self.w3c_actions.pointer_action.move_to(to_element)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
  File "C:\Users\kasun\AppData\Local\Programs\Python\Python313\Lib\site-packages\selenium\webdriver\common\actions\pointer_actions.py", line 88, in move_to
    raise AttributeError("move_to requires a WebElement")
AttributeError: move_to requires a WebElement

2024-12-25 17:38:16 - Logger - ERROR: 예상치 못한 예외 발생: AttributeError
2024-12-25 17:38:16 - Logger - INFO: 스크린샷 저장 완료: d:\test-rpa\screenshots\NoneType_기기추천영역None로마우스를이동하지못했습니다._20241225173816.png
2024-12-25 17:38:16 - Logger - ERROR: 기기 추천 영역 테스트 실패: TestCase03.create_locator() takes from 2 to 3 positional arguments but 4 were given
2024-12-25 17:38:16 - Logger - ERROR: Traceback (most recent call last):
  File "d:\test-rpa\pages\main.py", line 43, in execute
    device_tabs = find_elements(self.create_locator(self.driver, device_locator, " .tab-wrap ul li"), f"기기 추천 탭")
                                ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: TestCase03.create_locator() takes from 2 to 3 positional arguments but 4 were given

2024-12-25 17:38:16 - Logger - ERROR: 예상치 못한 예외 발생: TypeError
2024-12-25 17:38:16 - Logger - INFO: 스크린샷 저장 완료: d:\test-rpa\screenshots\TestCase03_기기추천영역테스트실패_20241225173816.png
2024-12-25 17:38:16 - Logger - ERROR: ===================================테스트 케이스 실행 실패: TestCase03 - TestCase03.create_locator() takes from 2 to 3 positional arguments but 4 were given===================================
2024-12-25 17:52:17 - Logger - INFO: ===================================테스트 케이스 실행 시작: TestCase03===================================
2024-12-25 17:52:17 - Logger - INFO: 기기 추천 영역('css selector', 'div.device-section')(을)를 찾았습니다.
2024-12-25 17:52:18 - Logger - INFO: 기기 추천 영역 <selenium.webdriver.remote.webelement.WebElement (session="32f5c9370a2230ea2180314e1886e149", element="f.7B33FDD8A2421C1653116369B287CD47.d.F636C270C1B3861AA48512F07260119E.e.2763")>로 마우스를 이동했습니다.
2024-12-25 17:52:18 - Logger - ERROR: 기기 추천 영역 테스트 실패: TestCase03.create_locator() takes from 2 to 3 positional arguments but 4 were given
2024-12-25 17:52:18 - Logger - ERROR: Traceback (most recent call last):
  File "d:\test-rpa\pages\main.py", line 43, in execute
    device_tabs = find_elements(self.create_locator(self.driver, device_locator, " .tab-wrap ul li"), f"기기 추천 탭")
                                ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: TestCase03.create_locator() takes from 2 to 3 positional arguments but 4 were given

2024-12-25 17:52:18 - Logger - ERROR: 예상치 못한 예외 발생: TypeError
2024-12-25 17:52:18 - Logger - INFO: 스크린샷 저장 완료: d:\test-rpa\screenshots\TestCase03_기기추천영역테스트실패_20241225175218.png
2024-12-25 17:52:18 - Logger - ERROR: ===================================테스트 케이스 실행 실패: TestCase03 - TestCase03.create_locator() takes from 2 to 3 positional arguments but 4 were given===================================
2024-12-25 18:34:49 - Logger - INFO: ===================================테스트 케이스 실행 시작: TestCase03===================================
2024-12-25 18:34:49 - Logger - INFO: 기기 추천 영역('css selector', 'div.device-section')(을)를 찾았습니다.
2024-12-25 18:34:51 - Logger - INFO: 기기 추천 영역<selenium.webdriver.remote.webelement.WebElement (session="d95edca402494ea7a6d8bc8069361c41", element="f.E6CD2C2C441880CE8DF93287BF2CB3F7.d.4A5C6CFFF2C89BB746B28264B6D3EF91.e.2622")>로 마우스를 이동했습니다.
2024-12-25 18:34:51 - Logger - ERROR: 기기 추천 영역 테스트 실패: TestCase03.create_locator() takes from 2 to 3 positional arguments but 4 were given
2024-12-25 18:34:51 - Logger - ERROR: Traceback (most recent call last):
  File "d:\test-rpa\pages\main.py", line 43, in execute
    device_tabs = find_elements(self.create_locator(self.driver, device_locator, " .tab-wrap ul li"), f"기기 추천 탭")
                                ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: TestCase03.create_locator() takes from 2 to 3 positional arguments but 4 were given

2024-12-25 18:34:51 - Logger - ERROR: 예상치 못한 예외 발생: TypeError
2024-12-25 18:34:51 - Logger - INFO: 스크린샷 저장 완료: d:\test-rpa\screenshots\TestCase03_기기추천영역테스트실패_20241225183451.png
2024-12-25 18:34:51 - Logger - ERROR: ===================================테스트 케이스 실행 실패: TestCase03 - TestCase03.create_locator() takes from 2 to 3 positional arguments but 4 were given===================================
2024-12-25 19:13:57 - Logger - INFO: ===================================테스트 케이스 실행 시작: TestCase03===================================
2024-12-25 19:13:57 - Logger - INFO: 기기 추천 영역('css selector', 'div.device-section')(을)를 찾았습니다.
2024-12-25 19:13:59 - Logger - INFO: 기기 추천 영역<selenium.webdriver.remote.webelement.WebElement (session="d164f8d4764a1859103344b34018055c", element="f.89FDFCD1FD6D99F1A90FCC1DA02028D6.d.D1E1F9DC53C4FA766926E5C384A71352.e.2959")>로 마우스를 이동했습니다.
2024-12-25 19:13:59 - Logger - ERROR: 기기 추천 영역 테스트 실패: TestCase03.create_locator() takes from 2 to 3 positional arguments but 4 were given
2024-12-25 19:13:59 - Logger - ERROR: Traceback (most recent call last):
  File "d:\test-rpa\pages\main.py", line 41, in execute
    device_tabs = find_elements(self.create_locator(self.driver, 'device_section', " .tab-wrap ul li"), f"기기 추천 탭")
                                ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: TestCase03.create_locator() takes from 2 to 3 positional arguments but 4 were given

2024-12-25 19:13:59 - Logger - ERROR: 예상치 못한 예외 발생: TypeError
2024-12-25 19:13:59 - Logger - INFO: 스크린샷 저장 완료: d:\test-rpa\screenshots\TestCase03_기기추천영역테스트실패_20241225191359.png
2024-12-25 19:13:59 - Logger - ERROR: ===================================테스트 케이스 실행 실패: TestCase03 - TestCase03.create_locator() takes from 2 to 3 positional arguments but 4 were given===================================
2024-12-25 19:21:49 - Logger - INFO: ===================================테스트 케이스 실행 시작: TestCase03===================================
2024-12-25 19:21:49 - Logger - ERROR: 기기 추천 영역div.device-section(이)가 화면에 보이지 않습니다.: WebDriver.find_element() takes from 1 to 3 positional arguments but 19 were given
2024-12-25 19:21:49 - Logger - ERROR: Traceback (most recent call last):
  File "d:\test-rpa\utils\custom_utils.py", line 30, in find_visible_element
    element = WebDriverWait(driver, EXPLICIT_WAIT).until(
        EC.presence_of_element_located(locator)  # 요소가 존재하는지 확인
    )
  File "C:\Users\kasun\AppData\Local\Programs\Python\Python313\Lib\site-packages\selenium\webdriver\support\wait.py", line 96, in until
    value = method(self._driver)
  File "C:\Users\kasun\AppData\Local\Programs\Python\Python313\Lib\site-packages\selenium\webdriver\support\expected_conditions.py", line 84, in _predicate
    return driver.find_element(*locator)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
TypeError: WebDriver.find_element() takes from 1 to 3 positional arguments but 19 were given

2024-12-25 19:21:49 - Logger - ERROR: 예상치 못한 예외 발생: TypeError
2024-12-25 19:21:49 - Logger - INFO: 스크린샷 저장 완료: d:\test-rpa\screenshots\NoneType_기기추천영역div.device-section(이)가화면에보이지않습니다._20241225192149.png
2024-12-25 19:21:49 - Logger - ERROR: 기기 추천 영역None로 마우스를 이동하지 못했습니다.: move_to requires a WebElement
2024-12-25 19:21:49 - Logger - ERROR: Traceback (most recent call last):
  File "d:\test-rpa\utils\custom_utils.py", line 91, in move_to_element
    actions.move_to_element(locator).perform()
    ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\kasun\AppData\Local\Programs\Python\Python313\Lib\site-packages\selenium\webdriver\common\action_chains.py", line 253, in move_to_element
    self.w3c_actions.pointer_action.move_to(to_element)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
  File "C:\Users\kasun\AppData\Local\Programs\Python\Python313\Lib\site-packages\selenium\webdriver\common\actions\pointer_actions.py", line 88, in move_to
    raise AttributeError("move_to requires a WebElement")
AttributeError: move_to requires a WebElement

2024-12-25 19:21:49 - Logger - ERROR: 예상치 못한 예외 발생: AttributeError
2024-12-25 19:21:49 - Logger - INFO: 스크린샷 저장 완료: d:\test-rpa\screenshots\NoneType_기기추천영역None로마우스를이동하지못했습니다._20241225192149.png
2024-12-25 19:21:49 - Logger - ERROR: 기기 추천 영역 테스트 실패: TestCase03.get_locator() takes from 2 to 3 positional arguments but 4 were given
2024-12-25 19:21:49 - Logger - ERROR: Traceback (most recent call last):
  File "d:\test-rpa\pages\main.py", line 49, in execute
    device_tabs = find_elements(self.get_locator(self.driver, device_locator, " .tab-wrap ul li"), f"기기 추천 탭")
                                ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: TestCase03.get_locator() takes from 2 to 3 positional arguments but 4 were given

2024-12-25 19:21:49 - Logger - ERROR: 예상치 못한 예외 발생: TypeError
2024-12-25 19:21:49 - Logger - INFO: 스크린샷 저장 완료: d:\test-rpa\screenshots\TestCase03_기기추천영역테스트실패_20241225192149.png
2024-12-25 19:21:49 - Logger - ERROR: ===================================테스트 케이스 실행 실패: TestCase03 - TestCase03.get_locator() takes from 2 to 3 positional arguments but 4 were given===================================
2024-12-25 19:27:28 - Logger - INFO: ===================================테스트 케이스 실행 시작: TestCase03===================================
2024-12-25 19:27:28 - Logger - ERROR: 기기 추천 영역div.device-section(이)가 화면에 보이지 않습니다.: WebDriver.find_element() takes from 1 to 3 positional arguments but 19 were given
2024-12-25 19:27:28 - Logger - ERROR: Traceback (most recent call last):
  File "d:\test-rpa\utils\custom_utils.py", line 30, in find_visible_element
    element = WebDriverWait(driver, EXPLICIT_WAIT).until(
        EC.presence_of_element_located(locator)  # 요소가 존재하는지 확인
    )
  File "C:\Users\kasun\AppData\Local\Programs\Python\Python313\Lib\site-packages\selenium\webdriver\support\wait.py", line 96, in until
    value = method(self._driver)
  File "C:\Users\kasun\AppData\Local\Programs\Python\Python313\Lib\site-packages\selenium\webdriver\support\expected_conditions.py", line 84, in _predicate
    return driver.find_element(*locator)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
TypeError: WebDriver.find_element() takes from 1 to 3 positional arguments but 19 were given

2024-12-25 19:27:28 - Logger - ERROR: 예상치 못한 예외 발생: TypeError
2024-12-25 19:27:28 - Logger - INFO: 스크린샷 저장 완료: d:\test-rpa\screenshots\NoneType_기기추천영역div.device-section(이)가화면에보이지않습니다._20241225192728.png
2024-12-25 19:27:28 - Logger - ERROR: 기기 추천 영역None로 마우스를 이동하지 못했습니다.: move_to requires a WebElement
2024-12-25 19:27:28 - Logger - ERROR: Traceback (most recent call last):
  File "d:\test-rpa\utils\custom_utils.py", line 91, in move_to_element
    actions.move_to_element(locator).perform()
    ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\kasun\AppData\Local\Programs\Python\Python313\Lib\site-packages\selenium\webdriver\common\action_chains.py", line 253, in move_to_element
    self.w3c_actions.pointer_action.move_to(to_element)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
  File "C:\Users\kasun\AppData\Local\Programs\Python\Python313\Lib\site-packages\selenium\webdriver\common\actions\pointer_actions.py", line 88, in move_to
    raise AttributeError("move_to requires a WebElement")
AttributeError: move_to requires a WebElement

2024-12-25 19:27:28 - Logger - ERROR: 예상치 못한 예외 발생: AttributeError
2024-12-25 19:27:28 - Logger - INFO: 스크린샷 저장 완료: d:\test-rpa\screenshots\NoneType_기기추천영역None로마우스를이동하지못했습니다._20241225192728.png
2024-12-25 19:27:28 - Logger - ERROR: 기기 추천 영역 테스트 실패: TestCase03.get_locator() takes from 2 to 3 positional arguments but 4 were given
2024-12-25 19:27:28 - Logger - ERROR: Traceback (most recent call last):
  File "d:\test-rpa\pages\main.py", line 49, in execute
    device_tabs = find_elements(self.get_locator(self.driver, device_locator, " .tab-wrap ul li"), f"기기 추천 탭")
                                ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: TestCase03.get_locator() takes from 2 to 3 positional arguments but 4 were given

2024-12-25 19:27:28 - Logger - ERROR: 예상치 못한 예외 발생: TypeError
2024-12-25 19:27:29 - Logger - INFO: 스크린샷 저장 완료: d:\test-rpa\screenshots\TestCase03_기기추천영역테스트실패_20241225192728.png
2024-12-25 19:27:29 - Logger - ERROR: ===================================테스트 케이스 실행 실패: TestCase03 - TestCase03.get_locator() takes from 2 to 3 positional arguments but 4 were given===================================
2024-12-25 19:39:21 - Logger - INFO: ===================================테스트 케이스 실행 시작: TestCase03===================================
2024-12-25 19:39:21 - Logger - INFO: 기기 추천 영역('css selector', 'div.device-section')(을)를 찾았습니다.
2024-12-25 19:39:22 - Logger - INFO: 기기 추천 영역<selenium.webdriver.remote.webelement.WebElement (session="b5a4611601242034e145f88d48529038", element="f.ABC806582B086C24300C4195D2FF899F.d.B81AA51AB8C8EBC953050A014E75BD1D.e.2776")>로 마우스를 이동했습니다.
2024-12-25 19:39:22 - Logger - ERROR: 기기 추천 영역 테스트 실패: TestCase03.create_locator() takes from 2 to 3 positional arguments but 4 were given
2024-12-25 19:39:22 - Logger - ERROR: Traceback (most recent call last):
  File "d:\test-rpa\pages\main.py", line 41, in execute
    device_tabs = find_elements(self.create_locator(self.driver, device_locator, " .tab-wrap ul li"), f"기기 추천 탭")
                                ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: TestCase03.create_locator() takes from 2 to 3 positional arguments but 4 were given

2024-12-25 19:39:22 - Logger - ERROR: 예상치 못한 예외 발생: TypeError
2024-12-25 19:39:23 - Logger - INFO: 스크린샷 저장 완료: d:\test-rpa\screenshots\TestCase03_기기추천영역테스트실패_20241225193922.png
2024-12-25 19:39:23 - Logger - ERROR: ===================================테스트 케이스 실행 실패: TestCase03 - TestCase03.create_locator() takes from 2 to 3 positional arguments but 4 were given===================================
2024-12-25 19:41:00 - Logger - INFO: ===================================테스트 케이스 실행 시작: TestCase03===================================
2024-12-25 19:41:00 - Logger - INFO: 기기 추천 영역('css selector', 'div.device-section')(을)를 찾았습니다.
2024-12-25 19:41:01 - Logger - INFO: 기기 추천 영역<selenium.webdriver.remote.webelement.WebElement (session="f23fbff84bba28b8a71448285aaefb2f", element="f.6D7258BC51F51145A8671D5266DAAEA3.d.6B48D25C5B87AE369ED6CCF62D047F15.e.2329")>로 마우스를 이동했습니다.
2024-12-25 19:41:01 - Logger - ERROR: 기기 추천 영역 테스트 실패: TestCase03.create_locator() takes from 2 to 3 positional arguments but 4 were given
2024-12-25 19:41:01 - Logger - ERROR: Traceback (most recent call last):
  File "d:\test-rpa\pages\main.py", line 41, in execute
    device_tabs = find_elements(self.create_locator(self.driver, device_locator, " .tab-wrap ul li"), f"기기 추천 탭")
                                ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: TestCase03.create_locator() takes from 2 to 3 positional arguments but 4 were given

2024-12-25 19:41:01 - Logger - ERROR: 예상치 못한 예외 발생: TypeError
2024-12-25 19:41:01 - Logger - INFO: 스크린샷 저장 완료: d:\test-rpa\screenshots\TestCase03_기기추천영역테스트실패_20241225194101.png
2024-12-25 19:41:01 - Logger - ERROR: ===================================테스트 케이스 실행 실패: TestCase03 - TestCase03.create_locator() takes from 2 to 3 positional arguments but 4 were given===================================
2024-12-25 19:41:51 - Logger - INFO: ===================================테스트 케이스 실행 시작: TestCase03===================================
2024-12-25 19:41:51 - Logger - INFO: 기기 추천 영역('css selector', 'div.device-section')(을)를 찾았습니다.
2024-12-25 19:41:52 - Logger - INFO: 기기 추천 영역<selenium.webdriver.remote.webelement.WebElement (session="5394cb0d1450525d02d112683d383731", element="f.305667EE1A6558387D3E3903284AED59.d.193EB03EA63454A4F6ECFC817ED4E318.e.2645")>로 마우스를 이동했습니다.
2024-12-25 19:41:52 - Logger - ERROR: 기기 추천 영역 테스트 실패: TestCase03.create_locator() takes from 2 to 3 positional arguments but 4 were given
2024-12-25 19:41:52 - Logger - ERROR: Traceback (most recent call last):
  File "d:\test-rpa\pages\main.py", line 41, in execute
    device_tabs = find_elements(self.driver, self.create_locator(self.driver, device_locator, " .tab-wrap ul li"), f"기기 추천 탭")
                                             ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: TestCase03.create_locator() takes from 2 to 3 positional arguments but 4 were given

2024-12-25 19:41:52 - Logger - ERROR: 예상치 못한 예외 발생: TypeError
2024-12-25 19:41:52 - Logger - INFO: 스크린샷 저장 완료: d:\test-rpa\screenshots\TestCase03_기기추천영역테스트실패_20241225194152.png
2024-12-25 19:41:52 - Logger - ERROR: ===================================테스트 케이스 실행 실패: TestCase03 - TestCase03.create_locator() takes from 2 to 3 positional arguments but 4 were given===================================
2024-12-25 19:44:13 - Logger - INFO: ===================================테스트 케이스 실행 시작: TestCase03===================================
2024-12-25 19:44:13 - Logger - INFO: 기기 추천 영역('css selector', 'div.device-section')(을)를 찾았습니다.
2024-12-25 19:44:14 - Logger - INFO: 기기 추천 영역<selenium.webdriver.remote.webelement.WebElement (session="67bfde3e848ed12180ba1e2bcea3d30b", element="f.FC56BDE353754D1FBDDE2C41F4180D40.d.52D4CA72005F5CC366BCAAF59E2A69EE.e.2328")>로 마우스를 이동했습니다.
2024-12-25 19:44:14 - Logger - ERROR: 기기 추천 영역 테스트 실패: TestCase03.create_locator() takes from 2 to 3 positional arguments but 4 were given
2024-12-25 19:44:14 - Logger - ERROR: Traceback (most recent call last):
  File "d:\test-rpa\pages\main.py", line 41, in execute
    device_tabs = find_elements(self.driver, *self.create_locator(self.driver, device_locator, " .tab-wrap ul li"), f"기기 추천 탭")
                                              ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: TestCase03.create_locator() takes from 2 to 3 positional arguments but 4 were given

2024-12-25 19:44:14 - Logger - ERROR: 예상치 못한 예외 발생: TypeError
2024-12-25 19:44:14 - Logger - INFO: 스크린샷 저장 완료: d:\test-rpa\screenshots\TestCase03_기기추천영역테스트실패_20241225194414.png
2024-12-25 19:44:14 - Logger - ERROR: ===================================테스트 케이스 실행 실패: TestCase03 - TestCase03.create_locator() takes from 2 to 3 positional arguments but 4 were given===================================
2024-12-25 19:55:02 - Logger - INFO: ===================================테스트 케이스 실행 시작: TestCase03===================================
2024-12-25 19:55:02 - Logger - ERROR: 기기 추천 영역 테스트 실패: <selenium.webdriver.chrome.webdriver.WebDriver (session="0509ec765e2b5cbb3f7224ee16d21e02")>
2024-12-25 19:55:02 - Logger - ERROR: Traceback (most recent call last):
  File "d:\test-rpa\pages\main.py", line 38, in execute
    device_section = find_element(self.driver, self.create_locator(self.driver, device_locator), f"기기 추천 영역")
                                               ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\test-rpa\pages\main.py", line 33, in create_locator
    return (By.CSS_SELECTOR, f"{self.locators[main_locator]}{sub_locator}")
                                ~~~~~~~~~~~~~^^^^^^^^^^^^^^
KeyError: <selenium.webdriver.chrome.webdriver.WebDriver (session="0509ec765e2b5cbb3f7224ee16d21e02")>

2024-12-25 19:55:02 - Logger - ERROR: 예상치 못한 예외 발생: KeyError
2024-12-25 19:55:02 - Logger - INFO: 스크린샷 저장 완료: d:\test-rpa\screenshots\TestCase03_기기추천영역테스트실패_20241225195502.png
2024-12-25 19:55:02 - Logger - ERROR: ===================================테스트 케이스 실행 실패: TestCase03 - <selenium.webdriver.chrome.webdriver.WebDriver (session="0509ec765e2b5cbb3f7224ee16d21e02")>===================================
2024-12-25 19:58:23 - Logger - INFO: ===================================테스트 케이스 실행 시작: TestCase03===================================
2024-12-25 19:58:23 - Logger - ERROR: 기기 추천 영역 테스트 실패: 'div.device-section'
2024-12-25 19:58:23 - Logger - ERROR: Traceback (most recent call last):
  File "d:\test-rpa\pages\main.py", line 38, in execute
    device_section = find_element(self.driver, self.create_locator(device_locator), f"기기 추천 영역")
                                               ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
  File "d:\test-rpa\pages\main.py", line 33, in create_locator
    return (By.CSS_SELECTOR, f"{self.locators[main_locator]}{sub_locator}")
                                ~~~~~~~~~~~~~^^^^^^^^^^^^^^
KeyError: 'div.device-section'

2024-12-25 19:58:23 - Logger - ERROR: 예상치 못한 예외 발생: KeyError
2024-12-25 19:58:23 - Logger - INFO: 스크린샷 저장 완료: d:\test-rpa\screenshots\TestCase03_기기추천영역테스트실패_20241225195823.png
2024-12-25 19:58:23 - Logger - ERROR: ===================================테스트 케이스 실행 실패: TestCase03 - 'div.device-section'===================================
2024-12-25 19:58:42 - Logger - INFO: ===================================테스트 케이스 실행 시작: TestCase03===================================
2024-12-25 19:58:42 - Logger - ERROR: 기기 추천 영역 테스트 실패: '기기추천영역'
2024-12-25 19:58:42 - Logger - ERROR: Traceback (most recent call last):
  File "d:\test-rpa\pages\main.py", line 38, in execute
    device_section = find_element(self.driver, self.create_locator("기기추천영역"), f"기기 추천 영역")
                                               ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
  File "d:\test-rpa\pages\main.py", line 33, in create_locator
    return (By.CSS_SELECTOR, f"{self.locators[main_locator]}{sub_locator}")
                                ~~~~~~~~~~~~~^^^^^^^^^^^^^^
KeyError: '기기추천영역'

2024-12-25 19:58:42 - Logger - ERROR: 예상치 못한 예외 발생: KeyError
2024-12-25 19:58:42 - Logger - INFO: 스크린샷 저장 완료: d:\test-rpa\screenshots\TestCase03_기기추천영역테스트실패_20241225195842.png
2024-12-25 19:58:42 - Logger - ERROR: ===================================테스트 케이스 실행 실패: TestCase03 - '기기추천영역'===================================
2024-12-25 19:59:03 - Logger - INFO: ===================================테스트 케이스 실행 시작: TestCase03===================================
2024-12-25 19:59:03 - Logger - INFO: 기기 추천 영역('css selector', 'div.device-section')(을)를 찾았습니다.
2024-12-25 19:59:04 - Logger - INFO: 기기 추천 영역<selenium.webdriver.remote.webelement.WebElement (session="cfaee5f5fa34dcf558c8488f7fc2cfe3", element="f.716D991DCCD41B8BDE0A747069295EA6.d.C105205A74207BD813531B82CFD85180.e.2608")>로 마우스를 이동했습니다.
2024-12-25 19:59:04 - Logger - INFO: ===================================테스트 케이스 실행 완료: TestCase03===================================
2024-12-25 19:59:52 - Logger - INFO: ===================================테스트 케이스 실행 시작: TestCase03===================================
2024-12-25 19:59:52 - Logger - ERROR: 기기 추천 영역 테스트 실패: <selenium.webdriver.chrome.webdriver.WebDriver (session="ff4705fa7d81365624b4fca20c6e25c2")>
2024-12-25 19:59:52 - Logger - ERROR: Traceback (most recent call last):
  File "d:\test-rpa\pages\main.py", line 38, in execute
    device_section = find_element(self.driver, self.create_locator(self.driver, self.locators['device_section']), f"기기 추천 영역")
                                               ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\test-rpa\pages\main.py", line 33, in create_locator
    return (By.CSS_SELECTOR, f"{self.locators[main_locator]}{sub_locator}")
                                ~~~~~~~~~~~~~^^^^^^^^^^^^^^
KeyError: <selenium.webdriver.chrome.webdriver.WebDriver (session="ff4705fa7d81365624b4fca20c6e25c2")>

2024-12-25 19:59:52 - Logger - ERROR: 예상치 못한 예외 발생: KeyError
2024-12-25 19:59:52 - Logger - INFO: 스크린샷 저장 완료: d:\test-rpa\screenshots\TestCase03_기기추천영역테스트실패_20241225195952.png
2024-12-25 19:59:52 - Logger - ERROR: ===================================테스트 케이스 실행 실패: TestCase03 - <selenium.webdriver.chrome.webdriver.WebDriver (session="ff4705fa7d81365624b4fca20c6e25c2")>===================================
2024-12-25 20:00:55 - Logger - INFO: ===================================테스트 케이스 실행 시작: TestCase03===================================
2024-12-25 20:00:55 - Logger - ERROR: 기기 추천 영역<bound method TestCase03.create_locator of <pages.main.TestCase03 object at 0x0000018D17A38EC0>>(을)를 찾지못했습니다.: selenium.webdriver.remote.webdriver.WebDriver.find_element() argument after * must be an iterable, not method
2024-12-25 20:00:55 - Logger - ERROR: Traceback (most recent call last):
  File "d:\test-rpa\utils\custom_utils.py", line 63, in find_element
    element = WebDriverWait(driver, EXPLICIT_WAIT).until(
        EC.presence_of_element_located(locator)
    )
  File "C:\Users\kasun\AppData\Local\Programs\Python\Python313\Lib\site-packages\selenium\webdriver\support\wait.py", line 96, in until
    value = method(self._driver)
  File "C:\Users\kasun\AppData\Local\Programs\Python\Python313\Lib\site-packages\selenium\webdriver\support\expected_conditions.py", line 84, in _predicate
    return driver.find_element(*locator)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
TypeError: selenium.webdriver.remote.webdriver.WebDriver.find_element() argument after * must be an iterable, not method

2024-12-25 20:00:55 - Logger - ERROR: 예상치 못한 예외 발생: TypeError
2024-12-25 20:00:56 - Logger - INFO: 스크린샷 저장 완료: d:\test-rpa\screenshots\NoneType_기기추천영역<boundmethodTestCase03.create_locatorof<pages.main.TestCase03objectat0x0000018D17A38EC0>>(을)를찾지못했습니다._20241225200055.png
2024-12-25 20:00:56 - Logger - ERROR: 기기 추천 영역None로 마우스를 이동하지 못했습니다.: move_to requires a WebElement
2024-12-25 20:00:56 - Logger - ERROR: Traceback (most recent call last):
  File "d:\test-rpa\utils\custom_utils.py", line 91, in move_to_element
    actions.move_to_element(locator).perform()
    ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\kasun\AppData\Local\Programs\Python\Python313\Lib\site-packages\selenium\webdriver\common\action_chains.py", line 253, in move_to_element
    self.w3c_actions.pointer_action.move_to(to_element)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
  File "C:\Users\kasun\AppData\Local\Programs\Python\Python313\Lib\site-packages\selenium\webdriver\common\actions\pointer_actions.py", line 88, in move_to
    raise AttributeError("move_to requires a WebElement")
AttributeError: move_to requires a WebElement

2024-12-25 20:00:56 - Logger - ERROR: 예상치 못한 예외 발생: AttributeError
2024-12-25 20:00:56 - Logger - INFO: 스크린샷 저장 완료: d:\test-rpa\screenshots\NoneType_기기추천영역None로마우스를이동하지못했습니다._20241225200056.png
2024-12-25 20:00:56 - Logger - INFO: ===================================테스트 케이스 실행 완료: TestCase03===================================
2024-12-25 20:02:33 - Logger - INFO: ===================================테스트 케이스 실행 시작: TestCase03===================================
2024-12-25 20:02:33 - Logger - ERROR: 기기 추천 영역 테스트 실패: find_element() takes from 2 to 3 positional arguments but 5 were given
2024-12-25 20:02:33 - Logger - ERROR: Traceback (most recent call last):
  File "d:\test-rpa\pages\main.py", line 38, in execute
    device_section = find_element(self.driver, self.create_locator,self.driver, self.locators['device_section'], f"기기 추천 영역")
                     ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: find_element() takes from 2 to 3 positional arguments but 5 were given

2024-12-25 20:02:33 - Logger - ERROR: 예상치 못한 예외 발생: TypeError
2024-12-25 20:02:33 - Logger - INFO: 스크린샷 저장 완료: d:\test-rpa\screenshots\TestCase03_기기추천영역테스트실패_20241225200233.png
2024-12-25 20:02:33 - Logger - ERROR: ===================================테스트 케이스 실행 실패: TestCase03 - find_element() takes from 2 to 3 positional arguments but 5 were given===================================
2024-12-25 20:04:53 - Logger - INFO: ===================================테스트 케이스 실행 시작: TestCase03===================================
2024-12-25 20:04:53 - Logger - ERROR: <bound method TestCase03.create_locator of <pages.main.TestCase03 object at 0x0000024083138EC0>>(을)를 찾지못했습니다.: selenium.webdriver.remote.webdriver.WebDriver.find_element() argument after * must be an iterable, not method
2024-12-25 20:04:53 - Logger - ERROR: Traceback (most recent call last):
  File "d:\test-rpa\utils\custom_utils.py", line 63, in find_element
    element = WebDriverWait(driver, EXPLICIT_WAIT).until(
        EC.presence_of_element_located(locator)
    )
  File "C:\Users\kasun\AppData\Local\Programs\Python\Python313\Lib\site-packages\selenium\webdriver\support\wait.py", line 96, in until
    value = method(self._driver)
  File "C:\Users\kasun\AppData\Local\Programs\Python\Python313\Lib\site-packages\selenium\webdriver\support\expected_conditions.py", line 84, in _predicate
    return driver.find_element(*locator)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
TypeError: selenium.webdriver.remote.webdriver.WebDriver.find_element() argument after * must be an iterable, not method

2024-12-25 20:04:53 - Logger - ERROR: 예상치 못한 예외 발생: TypeError
2024-12-25 20:04:53 - Logger - INFO: 스크린샷 저장 완료: d:\test-rpa\screenshots\NoneType_<boundmethodTestCase03.create_locatorof<pages.main.TestCase03objectat0x0000024083138EC0>>(을)를찾지못했습니다._20241225200453.png
2024-12-25 20:04:53 - Logger - ERROR: 기기 추천 영역None로 마우스를 이동하지 못했습니다.: move_to requires a WebElement
2024-12-25 20:04:53 - Logger - ERROR: Traceback (most recent call last):
  File "d:\test-rpa\utils\custom_utils.py", line 91, in move_to_element
    actions.move_to_element(locator).perform()
    ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\kasun\AppData\Local\Programs\Python\Python313\Lib\site-packages\selenium\webdriver\common\action_chains.py", line 253, in move_to_element
    self.w3c_actions.pointer_action.move_to(to_element)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
  File "C:\Users\kasun\AppData\Local\Programs\Python\Python313\Lib\site-packages\selenium\webdriver\common\actions\pointer_actions.py", line 88, in move_to
    raise AttributeError("move_to requires a WebElement")
AttributeError: move_to requires a WebElement

2024-12-25 20:04:53 - Logger - ERROR: 예상치 못한 예외 발생: AttributeError
2024-12-25 20:04:53 - Logger - INFO: 스크린샷 저장 완료: d:\test-rpa\screenshots\NoneType_기기추천영역None로마우스를이동하지못했습니다._20241225200453.png
2024-12-25 20:04:53 - Logger - INFO: ===================================테스트 케이스 실행 완료: TestCase03===================================
2024-12-25 20:06:22 - Logger - INFO: ===================================테스트 케이스 실행 시작: TestCase03===================================
2024-12-25 20:06:22 - Logger - ERROR: <bound method TestCase03.create_locator of <pages.main.TestCase03 object at 0x000002A162908EC0>>(을)를 찾지못했습니다.: selenium.webdriver.remote.webdriver.WebDriver.find_element() argument after * must be an iterable, not method
2024-12-25 20:06:22 - Logger - ERROR: Traceback (most recent call last):
  File "d:\test-rpa\utils\custom_utils.py", line 63, in find_element
    element = WebDriverWait(driver, EXPLICIT_WAIT).until(
        EC.presence_of_element_located(locator)
    )
  File "C:\Users\kasun\AppData\Local\Programs\Python\Python313\Lib\site-packages\selenium\webdriver\support\wait.py", line 96, in until
    value = method(self._driver)
  File "C:\Users\kasun\AppData\Local\Programs\Python\Python313\Lib\site-packages\selenium\webdriver\support\expected_conditions.py", line 84, in _predicate
    return driver.find_element(*locator)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
TypeError: selenium.webdriver.remote.webdriver.WebDriver.find_element() argument after * must be an iterable, not method

2024-12-25 20:06:22 - Logger - ERROR: 예상치 못한 예외 발생: TypeError
2024-12-25 20:06:22 - Logger - INFO: 스크린샷 저장 완료: d:\test-rpa\screenshots\NoneType_<boundmethodTestCase03.create_locatorof<pages.main.TestCase03objectat0x000002A162908EC0>>(을)를찾지못했습니다._20241225200622.png
2024-12-25 20:06:22 - Logger - ERROR: 기기 추천 영역None로 마우스를 이동하지 못했습니다.: move_to requires a WebElement
2024-12-25 20:06:22 - Logger - ERROR: Traceback (most recent call last):
  File "d:\test-rpa\utils\custom_utils.py", line 91, in move_to_element
    actions.move_to_element(locator).perform()
    ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\kasun\AppData\Local\Programs\Python\Python313\Lib\site-packages\selenium\webdriver\common\action_chains.py", line 253, in move_to_element
    self.w3c_actions.pointer_action.move_to(to_element)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
  File "C:\Users\kasun\AppData\Local\Programs\Python\Python313\Lib\site-packages\selenium\webdriver\common\actions\pointer_actions.py", line 88, in move_to
    raise AttributeError("move_to requires a WebElement")
AttributeError: move_to requires a WebElement

2024-12-25 20:06:22 - Logger - ERROR: 예상치 못한 예외 발생: AttributeError
2024-12-25 20:06:22 - Logger - INFO: 스크린샷 저장 완료: d:\test-rpa\screenshots\NoneType_기기추천영역None로마우스를이동하지못했습니다._20241225200622.png
2024-12-25 20:06:22 - Logger - INFO: ===================================테스트 케이스 실행 완료: TestCase03===================================
2024-12-25 20:09:08 - Logger - INFO: ===================================테스트 케이스 실행 시작: TestCase03===================================
2024-12-25 20:09:08 - Logger - ERROR: div.device-section(을)를 찾지못했습니다.: WebDriver.find_element() takes from 1 to 3 positional arguments but 19 were given
2024-12-25 20:09:08 - Logger - ERROR: Traceback (most recent call last):
  File "d:\test-rpa\utils\custom_utils.py", line 63, in find_element
    element = WebDriverWait(driver, EXPLICIT_WAIT).until(
        EC.presence_of_element_located(locator)
    )
  File "C:\Users\kasun\AppData\Local\Programs\Python\Python313\Lib\site-packages\selenium\webdriver\support\wait.py", line 96, in until
    value = method(self._driver)
  File "C:\Users\kasun\AppData\Local\Programs\Python\Python313\Lib\site-packages\selenium\webdriver\support\expected_conditions.py", line 84, in _predicate
    return driver.find_element(*locator)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
TypeError: WebDriver.find_element() takes from 1 to 3 positional arguments but 19 were given

2024-12-25 20:09:08 - Logger - ERROR: 예상치 못한 예외 발생: TypeError
2024-12-25 20:09:08 - Logger - INFO: 스크린샷 저장 완료: d:\test-rpa\screenshots\NoneType_div.device-section(을)를찾지못했습니다._20241225200908.png
2024-12-25 20:09:08 - Logger - ERROR: 기기 추천 영역None로 마우스를 이동하지 못했습니다.: move_to requires a WebElement
2024-12-25 20:09:08 - Logger - ERROR: Traceback (most recent call last):
  File "d:\test-rpa\utils\custom_utils.py", line 91, in move_to_element
    actions.move_to_element(locator).perform()
    ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\kasun\AppData\Local\Programs\Python\Python313\Lib\site-packages\selenium\webdriver\common\action_chains.py", line 253, in move_to_element
    self.w3c_actions.pointer_action.move_to(to_element)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
  File "C:\Users\kasun\AppData\Local\Programs\Python\Python313\Lib\site-packages\selenium\webdriver\common\actions\pointer_actions.py", line 88, in move_to
    raise AttributeError("move_to requires a WebElement")
AttributeError: move_to requires a WebElement

2024-12-25 20:09:08 - Logger - ERROR: 예상치 못한 예외 발생: AttributeError
2024-12-25 20:09:08 - Logger - INFO: 스크린샷 저장 완료: d:\test-rpa\screenshots\NoneType_기기추천영역None로마우스를이동하지못했습니다._20241225200908.png
2024-12-25 20:09:08 - Logger - INFO: ===================================테스트 케이스 실행 완료: TestCase03===================================
2024-12-25 20:09:23 - Logger - INFO: ===================================테스트 케이스 실행 시작: TestCase03===================================
2024-12-25 20:09:23 - Logger - INFO: ('css selector', 'div.device-section')(을)를 찾았습니다.
2024-12-25 20:09:24 - Logger - INFO: 기기 추천 영역<selenium.webdriver.remote.webelement.WebElement (session="6cf7c3c59e8a34ef2f5dcc780a1dea53", element="f.52DA103CA9CC979D8144CBB9D2134BC7.d.077C5E8EC4546B4698AF185F71089461.e.2285")>로 마우스를 이동했습니다.
2024-12-25 20:09:24 - Logger - INFO: ===================================테스트 케이스 실행 완료: TestCase03===================================
2024-12-25 20:10:21 - Logger - INFO: ===================================테스트 케이스 실행 시작: TestCase03===================================
2024-12-25 20:10:21 - Logger - INFO: ('css selector', 'div.device-section')(을)를 찾았습니다.
2024-12-25 20:10:22 - Logger - INFO: 기기 추천 영역<selenium.webdriver.remote.webelement.WebElement (session="46ced654230067519690a126fde983ad", element="f.B0EDDBF21AB06200C8717A1372D6047F.d.E8A7F1F39155A61685EAF047A9D6E835.e.2622")>로 마우스를 이동했습니다.
2024-12-25 20:10:22 - Logger - INFO: ===================================테스트 케이스 실행 완료: TestCase03===================================
2024-12-25 20:11:17 - Logger - INFO: ===================================테스트 케이스 실행 시작: TestCase03===================================
2024-12-25 20:11:17 - Logger - INFO: ('css selector', 'div.device-section')(을)를 찾았습니다.
2024-12-25 20:11:18 - Logger - INFO: 기기 추천 영역<selenium.webdriver.remote.webelement.WebElement (session="fd831c6a2437c4209c807ec754a4d945", element="f.CA49428B901118AFF1FB3E02BE912B29.d.EFDA5243019EA70D2BF5EEE77A92F18A.e.2679")>로 마우스를 이동했습니다.
2024-12-25 20:11:18 - Logger - ERROR: 기기 추천 탭('css selector', 'div.device-section', ' .tab-wrap ul li')들을 찾지못했습니다.: WebDriver.find_elements() takes from 1 to 3 positional arguments but 4 were given
2024-12-25 20:11:18 - Logger - ERROR: Traceback (most recent call last):
  File "d:\test-rpa\utils\custom_utils.py", line 76, in find_elements
    elements = WebDriverWait(driver, EXPLICIT_WAIT).until(
        EC.presence_of_all_elements_located(locator)
    )
  File "C:\Users\kasun\AppData\Local\Programs\Python\Python313\Lib\site-packages\selenium\webdriver\support\wait.py", line 96, in until
    value = method(self._driver)
  File "C:\Users\kasun\AppData\Local\Programs\Python\Python313\Lib\site-packages\selenium\webdriver\support\expected_conditions.py", line 191, in _predicate
    return driver.find_elements(*locator)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
TypeError: WebDriver.find_elements() takes from 1 to 3 positional arguments but 4 were given

2024-12-25 20:11:18 - Logger - ERROR: 예상치 못한 예외 발생: TypeError
2024-12-25 20:11:18 - Logger - INFO: 스크린샷 저장 완료: d:\test-rpa\screenshots\NoneType_기기추천탭('cssselector','div.device-section','.tab-wrapulli')들을찾지못했습니다._20241225201118.png
2024-12-25 20:11:18 - Logger - INFO: 기기 추천 탭: []
2024-12-25 20:11:18 - Logger - INFO: ===================================테스트 케이스 실행 완료: TestCase03===================================
2024-12-25 20:14:00 - Logger - INFO: ===================================테스트 케이스 실행 시작: TestCase03===================================
2024-12-25 20:14:00 - Logger - INFO: 기기 추천 영역('css selector', 'div.device-section')(을)를 찾았습니다.
2024-12-25 20:14:01 - Logger - INFO: 기기 추천 영역<selenium.webdriver.remote.webelement.WebElement (session="982714f3ab4b085c038392cdf5132991", element="f.EEE77FCA2415BAB89B9AAC3B13F7F250.d.16E499FA523C660AFA244CB2B7BF3710.e.2959")>로 마우스를 이동했습니다.
2024-12-25 20:14:05 - Logger - ERROR: 기기 추천 탭('css selector', 'div.device-section.tab-wrap ul li')들을 찾지못했습니다.: Message: no such window: target window already closed
from unknown error: web view not found
  (Session info: chrome=131.0.6778.205)
Stacktrace:
	GetHandleVerifier [0x00007FF652DCFB05+28789]
	(No symbol) [0x00007FF652D386E0]
	(No symbol) [0x00007FF652BD592A]
	(No symbol) [0x00007FF652BAF505]
	(No symbol) [0x00007FF652C56477]
	(No symbol) [0x00007FF652C6EF42]
	(No symbol) [0x00007FF652C4F1E3]
	(No symbol) [0x00007FF652C1A938]
	(No symbol) [0x00007FF652C1BAA1]
	GetHandleVerifier [0x00007FF65310933D+3410093]
	GetHandleVerifier [0x00007FF65311E7DD+3497293]
	GetHandleVerifier [0x00007FF653112A73+3448803]
	GetHandleVerifier [0x00007FF652E97BBB+848171]
	(No symbol) [0x00007FF652D43C3F]
	(No symbol) [0x00007FF652D3F6E4]
	(No symbol) [0x00007FF652D3F87D]
	(No symbol) [0x00007FF652D2ED49]
	BaseThreadInitThunk [0x00007FFC121D259D+29]
	RtlUserThreadStart [0x00007FFC13EAAF38+40]

2024-12-25 20:14:06 - Logger - ERROR: Traceback (most recent call last):
  File "d:\test-rpa\utils\custom_utils.py", line 76, in find_elements
    elements = WebDriverWait(driver, EXPLICIT_WAIT).until(
        EC.presence_of_all_elements_located(locator)
    )
  File "C:\Users\kasun\AppData\Local\Programs\Python\Python313\Lib\site-packages\selenium\webdriver\support\wait.py", line 96, in until
    value = method(self._driver)
  File "C:\Users\kasun\AppData\Local\Programs\Python\Python313\Lib\site-packages\selenium\webdriver\support\expected_conditions.py", line 191, in _predicate
    return driver.find_elements(*locator)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
  File "C:\Users\kasun\AppData\Local\Programs\Python\Python313\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 792, in find_elements
    return self.execute(Command.FIND_ELEMENTS, {"using": by, "value": value})["value"] or []
           ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kasun\AppData\Local\Programs\Python\Python313\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 384, in execute
    self.error_handler.check_response(response)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
  File "C:\Users\kasun\AppData\Local\Programs\Python\Python313\Lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 232, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchWindowException: Message: no such window: target window already closed
from unknown error: web view not found
  (Session info: chrome=131.0.6778.205)
Stacktrace:
	GetHandleVerifier [0x00007FF652DCFB05+28789]
	(No symbol) [0x00007FF652D386E0]
	(No symbol) [0x00007FF652BD592A]
	(No symbol) [0x00007FF652BAF505]
	(No symbol) [0x00007FF652C56477]
	(No symbol) [0x00007FF652C6EF42]
	(No symbol) [0x00007FF652C4F1E3]
	(No symbol) [0x00007FF652C1A938]
	(No symbol) [0x00007FF652C1BAA1]
	GetHandleVerifier [0x00007FF65310933D+3410093]
	GetHandleVerifier [0x00007FF65311E7DD+3497293]
	GetHandleVerifier [0x00007FF653112A73+3448803]
	GetHandleVerifier [0x00007FF652E97BBB+848171]
	(No symbol) [0x00007FF652D43C3F]
	(No symbol) [0x00007FF652D3F6E4]
	(No symbol) [0x00007FF652D3F87D]
	(No symbol) [0x00007FF652D2ED49]
	BaseThreadInitThunk [0x00007FFC121D259D+29]
	RtlUserThreadStart [0x00007FFC13EAAF38+40]


2024-12-25 20:14:06 - Logger - ERROR: 예상치 못한 예외 발생: NoSuchWindowException
2024-12-25 20:14:06 - Logger - INFO: 기기 추천 탭: []
2024-12-25 20:14:06 - Logger - INFO: ===================================테스트 케이스 실행 완료: TestCase03===================================
2024-12-25 20:14:34 - Logger - INFO: ===================================테스트 케이스 실행 시작: TestCase03===================================
2024-12-25 20:14:34 - Logger - INFO: 기기 추천 영역('css selector', 'div.device-section')(을)를 찾았습니다.
2024-12-25 20:14:35 - Logger - INFO: 기기 추천 영역<selenium.webdriver.remote.webelement.WebElement (session="ce979d5b975fb6f9c022e1bf69b2705f", element="f.51CB940C7664743B33FD1DABE3B6B14E.d.0C1B10500B57FBA30FBBB58A20F91305.e.2668")>로 마우스를 이동했습니다.
2024-12-25 20:14:35 - Logger - INFO: 기기 추천 탭('css selector', 'div.device-section .tab-wrap ul li')들을 3개 찾았습니다.
2024-12-25 20:14:35 - Logger - INFO: 기기 추천 탭: [<selenium.webdriver.remote.webelement.WebElement (session="ce979d5b975fb6f9c022e1bf69b2705f", element="f.51CB940C7664743B33FD1DABE3B6B14E.d.0C1B10500B57FBA30FBBB58A20F91305.e.2424")>, <selenium.webdriver.remote.webelement.WebElement (session="ce979d5b975fb6f9c022e1bf69b2705f", element="f.51CB940C7664743B33FD1DABE3B6B14E.d.0C1B10500B57FBA30FBBB58A20F91305.e.2426")>, <selenium.webdriver.remote.webelement.WebElement (session="ce979d5b975fb6f9c022e1bf69b2705f", element="f.51CB940C7664743B33FD1DABE3B6B14E.d.0C1B10500B57FBA30FBBB58A20F91305.e.2428")>]
2024-12-25 20:14:35 - Logger - INFO: ===================================테스트 케이스 실행 완료: TestCase03===================================
2024-12-25 20:15:29 - Logger - INFO: ===================================테스트 케이스 실행 시작: TestCase03===================================
2024-12-25 20:15:29 - Logger - ERROR: 기기 추천 영역 테스트 실패: <selenium.webdriver.chrome.webdriver.WebDriver (session="503cb124dc6db392c7d021f27dc84f3d")>
2024-12-25 20:15:29 - Logger - ERROR: Traceback (most recent call last):
  File "d:\test-rpa\pages\main.py", line 38, in execute
    device_section = find_element(self.driver, self.create_locator(self.driver, device_locator), f"기기 추천 영역")
                                               ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\test-rpa\pages\main.py", line 33, in create_locator
    return (By.CSS_SELECTOR, f"{self.locators[main_locator]}{sub_locator}")
                                ~~~~~~~~~~~~~^^^^^^^^^^^^^^
KeyError: <selenium.webdriver.chrome.webdriver.WebDriver (session="503cb124dc6db392c7d021f27dc84f3d")>

2024-12-25 20:15:29 - Logger - ERROR: 예상치 못한 예외 발생: KeyError
2024-12-25 20:15:29 - Logger - INFO: 스크린샷 저장 완료: d:\test-rpa\screenshots\TestCase03_기기추천영역테스트실패_20241225201529.png
2024-12-25 20:15:29 - Logger - ERROR: ===================================테스트 케이스 실행 실패: TestCase03 - <selenium.webdriver.chrome.webdriver.WebDriver (session="503cb124dc6db392c7d021f27dc84f3d")>===================================
2024-12-25 20:16:19 - Logger - INFO: ===================================테스트 케이스 실행 시작: TestCase03===================================
2024-12-25 20:16:19 - Logger - ERROR: 기기 추천 영역 테스트 실패: <selenium.webdriver.chrome.webdriver.WebDriver (session="0c2a49783ad538c08ff7c9b716383681")>
2024-12-25 20:16:19 - Logger - ERROR: Traceback (most recent call last):
  File "d:\test-rpa\pages\main.py", line 38, in execute
    device_section = find_element(self.driver, (self.create_locator(self.driver, device_locator)), f"기기 추천 영역")
                                                ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\test-rpa\pages\main.py", line 33, in create_locator
    return (By.CSS_SELECTOR, f"{self.locators[main_locator]}{sub_locator}")
                                ~~~~~~~~~~~~~^^^^^^^^^^^^^^
KeyError: <selenium.webdriver.chrome.webdriver.WebDriver (session="0c2a49783ad538c08ff7c9b716383681")>

2024-12-25 20:16:19 - Logger - ERROR: 예상치 못한 예외 발생: KeyError
2024-12-25 20:16:19 - Logger - INFO: 스크린샷 저장 완료: d:\test-rpa\screenshots\TestCase03_기기추천영역테스트실패_20241225201619.png
2024-12-25 20:16:19 - Logger - ERROR: ===================================테스트 케이스 실행 실패: TestCase03 - <selenium.webdriver.chrome.webdriver.WebDriver (session="0c2a49783ad538c08ff7c9b716383681")>===================================
2024-12-25 20:16:44 - Logger - INFO: ===================================테스트 케이스 실행 시작: TestCase03===================================
2024-12-25 20:16:44 - Logger - ERROR: 기기 추천 영역 테스트 실패: 'div.device-section'
2024-12-25 20:16:44 - Logger - ERROR: Traceback (most recent call last):
  File "d:\test-rpa\pages\main.py", line 38, in execute
    device_section = find_element(self.driver, (self.create_locator(device_locator)), f"기기 추천 영역")
                                                ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
  File "d:\test-rpa\pages\main.py", line 33, in create_locator
    return (By.CSS_SELECTOR, f"{self.locators[main_locator]}{sub_locator}")
                                ~~~~~~~~~~~~~^^^^^^^^^^^^^^
KeyError: 'div.device-section'

2024-12-25 20:16:44 - Logger - ERROR: 예상치 못한 예외 발생: KeyError
2024-12-25 20:16:44 - Logger - INFO: 스크린샷 저장 완료: d:\test-rpa\screenshots\TestCase03_기기추천영역테스트실패_20241225201644.png
2024-12-25 20:16:44 - Logger - ERROR: ===================================테스트 케이스 실행 실패: TestCase03 - 'div.device-section'===================================
2024-12-25 20:17:48 - Logger - INFO: ===================================테스트 케이스 실행 시작: TestCase03===================================
2024-12-25 20:19:12 - Logger - INFO: ===================================테스트 케이스 실행 시작: TestCase03===================================
2024-12-25 20:19:12 - Logger - ERROR: 기기 추천 영역('css selector', '<pages.main.TestCase03 object at 0x0000016BDF258EC0>div.device-section')(을)를 찾지못했습니다.: Message: invalid selector
from javascript error: {"status":32,"value":"An invalid or illegal selector was specified"}
  (Session info: chrome=131.0.6778.205); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#invalid-selector-exception
Stacktrace:
	GetHandleVerifier [0x00007FF652DCFB05+28789]
	(No symbol) [0x00007FF652D386E0]
	(No symbol) [0x00007FF652BD592A]
	(No symbol) [0x00007FF652BDC48F]
	(No symbol) [0x00007FF652BDF13C]
	(No symbol) [0x00007FF652BDF20F]
	(No symbol) [0x00007FF652C28DBA]
	(No symbol) [0x00007FF652C295FC]
	(No symbol) [0x00007FF652C728A7]
	(No symbol) [0x00007FF652C4F47F]
	(No symbol) [0x00007FF652C6F654]
	(No symbol) [0x00007FF652C4F1E3]
	(No symbol) [0x00007FF652C1A938]
	(No symbol) [0x00007FF652C1BAA1]
	GetHandleVerifier [0x00007FF65310933D+3410093]
	GetHandleVerifier [0x00007FF65311E7DD+3497293]
	GetHandleVerifier [0x00007FF653112A73+3448803]
	GetHandleVerifier [0x00007FF652E97BBB+848171]
	(No symbol) [0x00007FF652D43C3F]
	(No symbol) [0x00007FF652D3F6E4]
	(No symbol) [0x00007FF652D3F87D]
	(No symbol) [0x00007FF652D2ED49]
	BaseThreadInitThunk [0x00007FFC121D259D+29]
	RtlUserThreadStart [0x00007FFC13EAAF38+40]

2024-12-25 20:19:12 - Logger - ERROR: Traceback (most recent call last):
  File "d:\test-rpa\utils\custom_utils.py", line 63, in find_element
    element = WebDriverWait(driver, EXPLICIT_WAIT).until(
        EC.presence_of_element_located(locator)
    )
  File "C:\Users\kasun\AppData\Local\Programs\Python\Python313\Lib\site-packages\selenium\webdriver\support\wait.py", line 96, in until
    value = method(self._driver)
  File "C:\Users\kasun\AppData\Local\Programs\Python\Python313\Lib\site-packages\selenium\webdriver\support\expected_conditions.py", line 84, in _predicate
    return driver.find_element(*locator)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
  File "C:\Users\kasun\AppData\Local\Programs\Python\Python313\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 770, in find_element
    return self.execute(Command.FIND_ELEMENT, {"using": by, "value": value})["value"]
           ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kasun\AppData\Local\Programs\Python\Python313\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 384, in execute
    self.error_handler.check_response(response)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
  File "C:\Users\kasun\AppData\Local\Programs\Python\Python313\Lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 232, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.InvalidSelectorException: Message: invalid selector
from javascript error: {"status":32,"value":"An invalid or illegal selector was specified"}
  (Session info: chrome=131.0.6778.205); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#invalid-selector-exception
Stacktrace:
	GetHandleVerifier [0x00007FF652DCFB05+28789]
	(No symbol) [0x00007FF652D386E0]
	(No symbol) [0x00007FF652BD592A]
	(No symbol) [0x00007FF652BDC48F]
	(No symbol) [0x00007FF652BDF13C]
	(No symbol) [0x00007FF652BDF20F]
	(No symbol) [0x00007FF652C28DBA]
	(No symbol) [0x00007FF652C295FC]
	(No symbol) [0x00007FF652C728A7]
	(No symbol) [0x00007FF652C4F47F]
	(No symbol) [0x00007FF652C6F654]
	(No symbol) [0x00007FF652C4F1E3]
	(No symbol) [0x00007FF652C1A938]
	(No symbol) [0x00007FF652C1BAA1]
	GetHandleVerifier [0x00007FF65310933D+3410093]
	GetHandleVerifier [0x00007FF65311E7DD+3497293]
	GetHandleVerifier [0x00007FF653112A73+3448803]
	GetHandleVerifier [0x00007FF652E97BBB+848171]
	(No symbol) [0x00007FF652D43C3F]
	(No symbol) [0x00007FF652D3F6E4]
	(No symbol) [0x00007FF652D3F87D]
	(No symbol) [0x00007FF652D2ED49]
	BaseThreadInitThunk [0x00007FFC121D259D+29]
	RtlUserThreadStart [0x00007FFC13EAAF38+40]


2024-12-25 20:19:12 - Logger - ERROR: 예상치 못한 예외 발생: InvalidSelectorException
2024-12-25 20:19:13 - Logger - INFO: 스크린샷 저장 완료: d:\test-rpa\screenshots\NoneType_기기추천영역('cssselector','<pages.main.TestCase03objectat0x0000016BDF258EC0>div.device-section')(을)를찾지못했습니다._20241225201912.png
2024-12-25 20:19:13 - Logger - ERROR: 기기 추천 영역None로 마우스를 이동하지 못했습니다.: move_to requires a WebElement
2024-12-25 20:19:13 - Logger - ERROR: Traceback (most recent call last):
  File "d:\test-rpa\utils\custom_utils.py", line 91, in move_to_element
    actions.move_to_element(locator).perform()
    ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\kasun\AppData\Local\Programs\Python\Python313\Lib\site-packages\selenium\webdriver\common\action_chains.py", line 253, in move_to_element
    self.w3c_actions.pointer_action.move_to(to_element)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
  File "C:\Users\kasun\AppData\Local\Programs\Python\Python313\Lib\site-packages\selenium\webdriver\common\actions\pointer_actions.py", line 88, in move_to
    raise AttributeError("move_to requires a WebElement")
AttributeError: move_to requires a WebElement

2024-12-25 20:19:13 - Logger - ERROR: 예상치 못한 예외 발생: AttributeError
2024-12-25 20:19:13 - Logger - INFO: 스크린샷 저장 완료: d:\test-rpa\screenshots\NoneType_기기추천영역None로마우스를이동하지못했습니다._20241225201913.png
2024-12-25 20:19:13 - Logger - INFO: ===================================테스트 케이스 실행 완료: TestCase03===================================
2024-12-25 20:19:30 - Logger - INFO: ===================================테스트 케이스 실행 시작: TestCase03===================================
2024-12-25 20:19:30 - Logger - ERROR: 기기 추천 영역('css selector', '<pages.main.TestCase03 object at 0x00000227CF4A8EC0>div.device-section')(을)를 찾지못했습니다.: Message: invalid selector
from javascript error: {"status":32,"value":"An invalid or illegal selector was specified"}
  (Session info: chrome=131.0.6778.205); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#invalid-selector-exception
Stacktrace:
	GetHandleVerifier [0x00007FF652DCFB05+28789]
	(No symbol) [0x00007FF652D386E0]
	(No symbol) [0x00007FF652BD592A]
	(No symbol) [0x00007FF652BDC48F]
	(No symbol) [0x00007FF652BDF13C]
	(No symbol) [0x00007FF652BDF20F]
	(No symbol) [0x00007FF652C28DBA]
	(No symbol) [0x00007FF652C295FC]
	(No symbol) [0x00007FF652C728A7]
	(No symbol) [0x00007FF652C4F47F]
	(No symbol) [0x00007FF652C6F654]
	(No symbol) [0x00007FF652C4F1E3]
	(No symbol) [0x00007FF652C1A938]
	(No symbol) [0x00007FF652C1BAA1]
	GetHandleVerifier [0x00007FF65310933D+3410093]
	GetHandleVerifier [0x00007FF65311E7DD+3497293]
	GetHandleVerifier [0x00007FF653112A73+3448803]
	GetHandleVerifier [0x00007FF652E97BBB+848171]
	(No symbol) [0x00007FF652D43C3F]
	(No symbol) [0x00007FF652D3F6E4]
	(No symbol) [0x00007FF652D3F87D]
	(No symbol) [0x00007FF652D2ED49]
	BaseThreadInitThunk [0x00007FFC121D259D+29]
	RtlUserThreadStart [0x00007FFC13EAAF38+40]

2024-12-25 20:19:30 - Logger - ERROR: Traceback (most recent call last):
  File "d:\test-rpa\utils\custom_utils.py", line 63, in find_element
    element = WebDriverWait(driver, EXPLICIT_WAIT).until(
        EC.presence_of_element_located(locator)
    )
  File "C:\Users\kasun\AppData\Local\Programs\Python\Python313\Lib\site-packages\selenium\webdriver\support\wait.py", line 96, in until
    value = method(self._driver)
  File "C:\Users\kasun\AppData\Local\Programs\Python\Python313\Lib\site-packages\selenium\webdriver\support\expected_conditions.py", line 84, in _predicate
    return driver.find_element(*locator)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
  File "C:\Users\kasun\AppData\Local\Programs\Python\Python313\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 770, in find_element
    return self.execute(Command.FIND_ELEMENT, {"using": by, "value": value})["value"]
           ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kasun\AppData\Local\Programs\Python\Python313\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 384, in execute
    self.error_handler.check_response(response)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
  File "C:\Users\kasun\AppData\Local\Programs\Python\Python313\Lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 232, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.InvalidSelectorException: Message: invalid selector
from javascript error: {"status":32,"value":"An invalid or illegal selector was specified"}
  (Session info: chrome=131.0.6778.205); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#invalid-selector-exception
Stacktrace:
	GetHandleVerifier [0x00007FF652DCFB05+28789]
	(No symbol) [0x00007FF652D386E0]
	(No symbol) [0x00007FF652BD592A]
	(No symbol) [0x00007FF652BDC48F]
	(No symbol) [0x00007FF652BDF13C]
	(No symbol) [0x00007FF652BDF20F]
	(No symbol) [0x00007FF652C28DBA]
	(No symbol) [0x00007FF652C295FC]
	(No symbol) [0x00007FF652C728A7]
	(No symbol) [0x00007FF652C4F47F]
	(No symbol) [0x00007FF652C6F654]
	(No symbol) [0x00007FF652C4F1E3]
	(No symbol) [0x00007FF652C1A938]
	(No symbol) [0x00007FF652C1BAA1]
	GetHandleVerifier [0x00007FF65310933D+3410093]
	GetHandleVerifier [0x00007FF65311E7DD+3497293]
	GetHandleVerifier [0x00007FF653112A73+3448803]
	GetHandleVerifier [0x00007FF652E97BBB+848171]
	(No symbol) [0x00007FF652D43C3F]
	(No symbol) [0x00007FF652D3F6E4]
	(No symbol) [0x00007FF652D3F87D]
	(No symbol) [0x00007FF652D2ED49]
	BaseThreadInitThunk [0x00007FFC121D259D+29]
	RtlUserThreadStart [0x00007FFC13EAAF38+40]


2024-12-25 20:19:30 - Logger - ERROR: 예상치 못한 예외 발생: InvalidSelectorException
2024-12-25 20:19:30 - Logger - INFO: 스크린샷 저장 완료: d:\test-rpa\screenshots\NoneType_기기추천영역('cssselector','<pages.main.TestCase03objectat0x00000227CF4A8EC0>div.device-section')(을)를찾지못했습니다._20241225201930.png
2024-12-25 20:19:30 - Logger - ERROR: 기기 추천 영역None로 마우스를 이동하지 못했습니다.: move_to requires a WebElement
2024-12-25 20:19:30 - Logger - ERROR: Traceback (most recent call last):
  File "d:\test-rpa\utils\custom_utils.py", line 91, in move_to_element
    actions.move_to_element(locator).perform()
    ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\kasun\AppData\Local\Programs\Python\Python313\Lib\site-packages\selenium\webdriver\common\action_chains.py", line 253, in move_to_element
    self.w3c_actions.pointer_action.move_to(to_element)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
  File "C:\Users\kasun\AppData\Local\Programs\Python\Python313\Lib\site-packages\selenium\webdriver\common\actions\pointer_actions.py", line 88, in move_to
    raise AttributeError("move_to requires a WebElement")
AttributeError: move_to requires a WebElement

2024-12-25 20:19:30 - Logger - ERROR: 예상치 못한 예외 발생: AttributeError
2024-12-25 20:19:30 - Logger - INFO: 스크린샷 저장 완료: d:\test-rpa\screenshots\NoneType_기기추천영역None로마우스를이동하지못했습니다._20241225201930.png
2024-12-25 20:19:30 - Logger - INFO: ===================================테스트 케이스 실행 완료: TestCase03===================================
2024-12-25 20:19:53 - Logger - INFO: ===================================테스트 케이스 실행 시작: TestCase03===================================
2024-12-25 20:20:28 - Logger - INFO: ===================================테스트 케이스 실행 시작: TestCase03===================================
2024-12-25 20:20:34 - Logger - INFO: 기기 추천 영역('css selector', 'div.device-section')(을)를 찾았습니다.
2024-12-25 20:20:36 - Logger - INFO: 기기 추천 영역<selenium.webdriver.remote.webelement.WebElement (session="b2ccac700a3a43df2e77cd182c5d0113", element="f.E6D68085E545884CB42492C717FAB198.d.196C5CEE951BAAD596A8A7CF31342CA7.e.2604")>로 마우스를 이동했습니다.
2024-12-25 20:20:36 - Logger - INFO: ===================================테스트 케이스 실행 완료: TestCase03===================================
2024-12-25 20:22:05 - Logger - INFO: ===================================테스트 케이스 실행 시작: TestCase03===================================
2024-12-25 20:22:05 - Logger - ERROR: 기기 추천 영역 테스트 실패: TestCase03.create_locator() missing 1 required positional argument: 'main_locator'
2024-12-25 20:22:05 - Logger - ERROR: Traceback (most recent call last):
  File "D:\test-rpa\pages\main.py", line 38, in execute
    device_section = find_element(self.driver, (self.create_locator('device_section')), f"기기 추천 영역")
                                                ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
TypeError: TestCase03.create_locator() missing 1 required positional argument: 'main_locator'

2024-12-25 20:22:05 - Logger - ERROR: 예상치 못한 예외 발생: TypeError
2024-12-25 20:22:05 - Logger - INFO: 스크린샷 저장 완료: D:\test-rpa\screenshots\TestCase03_기기추천영역테스트실패_20241225202205.png
2024-12-25 20:22:05 - Logger - ERROR: ===================================테스트 케이스 실행 실패: TestCase03 - TestCase03.create_locator() missing 1 required positional argument: 'main_locator'===================================
2024-12-25 20:22:38 - Logger - INFO: ===================================테스트 케이스 실행 시작: TestCase03===================================
2024-12-25 20:22:38 - Logger - INFO: 기기 추천 영역('css selector', 'div.device-section')(을)를 찾았습니다.
2024-12-25 20:22:39 - Logger - INFO: 기기 추천 영역<selenium.webdriver.remote.webelement.WebElement (session="7684ebeadfd1447cca55dc6a57729f1f", element="f.C256E337A77AE7A92F9379106FA60631.d.F0A237C6A798C236F60CE37CD4B8C5A8.e.2473")>로 마우스를 이동했습니다.
2024-12-25 20:22:39 - Logger - INFO: ===================================테스트 케이스 실행 완료: TestCase03===================================
2024-12-25 20:23:47 - Logger - INFO: ===================================테스트 케이스 실행 시작: TestCase03===================================
2024-12-25 20:23:47 - Logger - INFO: 기기 추천 영역('css selector', 'div.device-section')(을)를 찾았습니다.
2024-12-25 20:23:49 - Logger - INFO: 기기 추천 영역<selenium.webdriver.remote.webelement.WebElement (session="067c92c4f79f6c3daae3e2c7b7e236bd", element="f.CB6272CF68A8363790E4CB0C16014CB1.d.2EDD9CA83136A3A3E1F8C89D45AB20CA.e.2623")>로 마우스를 이동했습니다.
2024-12-25 20:23:49 - Logger - ERROR: 기기 추천 탭('css selector', "('css selector', 'div.device-section') .tab-wrap ul li")들을 찾지못했습니다.: Message: invalid selector
from javascript error: {"status":32,"value":"An invalid or illegal selector was specified"}
  (Session info: chrome=131.0.6778.205); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#invalid-selector-exception
Stacktrace:
	GetHandleVerifier [0x00007FF652DCFB05+28789]
	(No symbol) [0x00007FF652D386E0]
	(No symbol) [0x00007FF652BD592A]
	(No symbol) [0x00007FF652BDC48F]
	(No symbol) [0x00007FF652BDF13C]
	(No symbol) [0x00007FF652BDF20F]
	(No symbol) [0x00007FF652C28DBA]
	(No symbol) [0x00007FF652C295FC]
	(No symbol) [0x00007FF652C728D7]
	(No symbol) [0x00007FF652C4F47F]
	(No symbol) [0x00007FF652C6F654]
	(No symbol) [0x00007FF652C4F1E3]
	(No symbol) [0x00007FF652C1A938]
	(No symbol) [0x00007FF652C1BAA1]
	GetHandleVerifier [0x00007FF65310933D+3410093]
	GetHandleVerifier [0x00007FF65311E7DD+3497293]
	GetHandleVerifier [0x00007FF653112A73+3448803]
	GetHandleVerifier [0x00007FF652E97BBB+848171]
	(No symbol) [0x00007FF652D43C3F]
	(No symbol) [0x00007FF652D3F6E4]
	(No symbol) [0x00007FF652D3F87D]
	(No symbol) [0x00007FF652D2ED49]
	BaseThreadInitThunk [0x00007FFC121D259D+29]
	RtlUserThreadStart [0x00007FFC13EAAF38+40]

2024-12-25 20:23:49 - Logger - ERROR: Traceback (most recent call last):
  File "d:\test-rpa\utils\custom_utils.py", line 76, in find_elements
    elements = WebDriverWait(driver, EXPLICIT_WAIT).until(
        EC.presence_of_all_elements_located(locator)
    )
  File "C:\Users\kasun\AppData\Local\Programs\Python\Python313\Lib\site-packages\selenium\webdriver\support\wait.py", line 96, in until
    value = method(self._driver)
  File "C:\Users\kasun\AppData\Local\Programs\Python\Python313\Lib\site-packages\selenium\webdriver\support\expected_conditions.py", line 191, in _predicate
    return driver.find_elements(*locator)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
  File "C:\Users\kasun\AppData\Local\Programs\Python\Python313\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 792, in find_elements
    return self.execute(Command.FIND_ELEMENTS, {"using": by, "value": value})["value"] or []
           ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kasun\AppData\Local\Programs\Python\Python313\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 384, in execute
    self.error_handler.check_response(response)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
  File "C:\Users\kasun\AppData\Local\Programs\Python\Python313\Lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 232, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.InvalidSelectorException: Message: invalid selector
from javascript error: {"status":32,"value":"An invalid or illegal selector was specified"}
  (Session info: chrome=131.0.6778.205); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#invalid-selector-exception
Stacktrace:
	GetHandleVerifier [0x00007FF652DCFB05+28789]
	(No symbol) [0x00007FF652D386E0]
	(No symbol) [0x00007FF652BD592A]
	(No symbol) [0x00007FF652BDC48F]
	(No symbol) [0x00007FF652BDF13C]
	(No symbol) [0x00007FF652BDF20F]
	(No symbol) [0x00007FF652C28DBA]
	(No symbol) [0x00007FF652C295FC]
	(No symbol) [0x00007FF652C728D7]
	(No symbol) [0x00007FF652C4F47F]
	(No symbol) [0x00007FF652C6F654]
	(No symbol) [0x00007FF652C4F1E3]
	(No symbol) [0x00007FF652C1A938]
	(No symbol) [0x00007FF652C1BAA1]
	GetHandleVerifier [0x00007FF65310933D+3410093]
	GetHandleVerifier [0x00007FF65311E7DD+3497293]
	GetHandleVerifier [0x00007FF653112A73+3448803]
	GetHandleVerifier [0x00007FF652E97BBB+848171]
	(No symbol) [0x00007FF652D43C3F]
	(No symbol) [0x00007FF652D3F6E4]
	(No symbol) [0x00007FF652D3F87D]
	(No symbol) [0x00007FF652D2ED49]
	BaseThreadInitThunk [0x00007FFC121D259D+29]
	RtlUserThreadStart [0x00007FFC13EAAF38+40]


2024-12-25 20:23:49 - Logger - ERROR: 예상치 못한 예외 발생: InvalidSelectorException
2024-12-25 20:23:49 - Logger - INFO: 스크린샷 저장 완료: d:\test-rpa\screenshots\NoneType_기기추천탭('cssselector',"('cssselector','div.device-section').tab-wrapulli")들을찾지못했습니다._20241225202349.png
2024-12-25 20:23:49 - Logger - INFO: 기기 추천 탭: []
2024-12-25 20:23:49 - Logger - INFO: ===================================테스트 케이스 실행 완료: TestCase03===================================
2024-12-25 20:24:20 - Logger - INFO: ===================================테스트 케이스 실행 시작: TestCase03===================================
2024-12-25 20:24:20 - Logger - INFO: 기기 추천 영역('css selector', 'div.device-section')(을)를 찾았습니다.
2024-12-25 20:24:22 - Logger - INFO: 기기 추천 영역<selenium.webdriver.remote.webelement.WebElement (session="af55aebcf51222def808dddfdc96335f", element="f.4C71AAEC6F62088F85902CC642821CB0.d.959C6CBE31F66EF9F6E331E30A95B09D.e.2328")>로 마우스를 이동했습니다.
2024-12-25 20:24:22 - Logger - ERROR: 기기 추천 탭('css selector', 'div.device-section') .tab-wrap ul li들을 찾지못했습니다.: WebDriver.find_elements() takes from 1 to 3 positional arguments but 55 were given
2024-12-25 20:24:22 - Logger - ERROR: Traceback (most recent call last):
  File "d:\test-rpa\utils\custom_utils.py", line 76, in find_elements
    elements = WebDriverWait(driver, EXPLICIT_WAIT).until(
        EC.presence_of_all_elements_located(locator)
    )
  File "C:\Users\kasun\AppData\Local\Programs\Python\Python313\Lib\site-packages\selenium\webdriver\support\wait.py", line 96, in until
    value = method(self._driver)
  File "C:\Users\kasun\AppData\Local\Programs\Python\Python313\Lib\site-packages\selenium\webdriver\support\expected_conditions.py", line 191, in _predicate
    return driver.find_elements(*locator)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
TypeError: WebDriver.find_elements() takes from 1 to 3 positional arguments but 55 were given

2024-12-25 20:24:22 - Logger - ERROR: 예상치 못한 예외 발생: TypeError
2024-12-25 20:24:22 - Logger - INFO: 스크린샷 저장 완료: d:\test-rpa\screenshots\NoneType_기기추천탭('cssselector','div.device-section').tab-wrapulli들을찾지못했습니다._20241225202422.png
2024-12-25 20:24:22 - Logger - INFO: 기기 추천 탭: []
2024-12-25 20:24:22 - Logger - INFO: ===================================테스트 케이스 실행 완료: TestCase03===================================
2024-12-25 20:25:24 - Logger - INFO: ===================================테스트 케이스 실행 시작: TestCase03===================================
2024-12-25 20:25:24 - Logger - INFO: 기기 추천 영역('css selector', 'div.device-section')(을)를 찾았습니다.
2024-12-25 20:25:25 - Logger - INFO: 기기 추천 영역<selenium.webdriver.remote.webelement.WebElement (session="a2ce370e46d114ae1aaa18f270982916", element="f.8FB972DAFD677134D631EEBFCC814464.d.4D7B79B9614B40DCEEE82654254683C3.e.2592")>로 마우스를 이동했습니다.
2024-12-25 20:25:25 - Logger - ERROR: 기기 추천 탭('css selector', 'div.device-section') .tab-wrap ul li들을 찾지못했습니다.: WebDriver.find_elements() takes from 1 to 3 positional arguments but 55 were given
2024-12-25 20:25:25 - Logger - ERROR: Traceback (most recent call last):
  File "d:\test-rpa\utils\custom_utils.py", line 76, in find_elements
    elements = WebDriverWait(driver, EXPLICIT_WAIT).until(
        EC.presence_of_all_elements_located(locator)
    )
  File "C:\Users\kasun\AppData\Local\Programs\Python\Python313\Lib\site-packages\selenium\webdriver\support\wait.py", line 96, in until
    value = method(self._driver)
  File "C:\Users\kasun\AppData\Local\Programs\Python\Python313\Lib\site-packages\selenium\webdriver\support\expected_conditions.py", line 191, in _predicate
    return driver.find_elements(*locator)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
TypeError: WebDriver.find_elements() takes from 1 to 3 positional arguments but 55 were given

2024-12-25 20:25:25 - Logger - ERROR: 예상치 못한 예외 발생: TypeError
2024-12-25 20:25:25 - Logger - INFO: 스크린샷 저장 완료: d:\test-rpa\screenshots\NoneType_기기추천탭('cssselector','div.device-section').tab-wrapulli들을찾지못했습니다._20241225202525.png
2024-12-25 20:25:25 - Logger - INFO: 기기 추천 탭: []
2024-12-25 20:25:25 - Logger - INFO: ===================================테스트 케이스 실행 완료: TestCase03===================================
2024-12-25 20:26:22 - Logger - INFO: ===================================테스트 케이스 실행 시작: TestCase03===================================
2024-12-25 20:26:22 - Logger - INFO: 기기 추천 영역('css selector', 'div.device-section')(을)를 찾았습니다.
2024-12-25 20:26:24 - Logger - INFO: 기기 추천 영역<selenium.webdriver.remote.webelement.WebElement (session="dd23eb17391fad2a1a9b1d71d4d00356", element="f.19D8D07DCA6A7C0A5C63D01590C3DA1D.d.AC558CF60AB358ACCD90D2351FD52595.e.2314")>로 마우스를 이동했습니다.
2024-12-25 20:26:24 - Logger - ERROR: 기기 추천 영역 테스트 실패: can only concatenate tuple (not "str") to tuple
2024-12-25 20:26:24 - Logger - ERROR: Traceback (most recent call last):
  File "d:\test-rpa\pages\main.py", line 41, in execute
    device_tabs = find_elements(self.driver, (self.create_locator('device_section') +" .tab-wrap ul li"), f"기기 추천 탭")
                                              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~
TypeError: can only concatenate tuple (not "str") to tuple

2024-12-25 20:26:24 - Logger - ERROR: 예상치 못한 예외 발생: TypeError
2024-12-25 20:26:24 - Logger - INFO: 스크린샷 저장 완료: d:\test-rpa\screenshots\TestCase03_기기추천영역테스트실패_20241225202624.png
2024-12-25 20:26:24 - Logger - ERROR: ===================================테스트 케이스 실행 실패: TestCase03 - can only concatenate tuple (not "str") to tuple===================================
2024-12-25 20:26:47 - Logger - INFO: ===================================테스트 케이스 실행 시작: TestCase03===================================
2024-12-25 20:26:47 - Logger - INFO: 기기 추천 영역('css selector', 'div.device-section')(을)를 찾았습니다.
2024-12-25 20:26:49 - Logger - INFO: 기기 추천 영역<selenium.webdriver.remote.webelement.WebElement (session="017b22edc93f32ec55d80d014891597d", element="f.5A1B8D03D0EA0B8D9DE88C4D2A65B859.d.487E18A263D0ED3DFD62680022A420CA.e.2464")>로 마우스를 이동했습니다.
2024-12-25 20:26:49 - Logger - ERROR: 기기 추천 탭(('css selector', 'div.device-section'), ' .tab-wrap ul li')들을 찾지못했습니다.: Message: invalid argument: 'using' must be a string
  (Session info: chrome=131.0.6778.205)
Stacktrace:
	GetHandleVerifier [0x00007FF652DCFB05+28789]
	(No symbol) [0x00007FF652D386E0]
	(No symbol) [0x00007FF652BD592A]
	(No symbol) [0x00007FF652C290C5]
	(No symbol) [0x00007FF652C295FC]
	(No symbol) [0x00007FF652C728D7]
	(No symbol) [0x00007FF652C4F47F]
	(No symbol) [0x00007FF652C6F654]
	(No symbol) [0x00007FF652C4F1E3]
	(No symbol) [0x00007FF652C1A938]
	(No symbol) [0x00007FF652C1BAA1]
	GetHandleVerifier [0x00007FF65310933D+3410093]
	GetHandleVerifier [0x00007FF65311E7DD+3497293]
	GetHandleVerifier [0x00007FF653112A73+3448803]
	GetHandleVerifier [0x00007FF652E97BBB+848171]
	(No symbol) [0x00007FF652D43C3F]
	(No symbol) [0x00007FF652D3F6E4]
	(No symbol) [0x00007FF652D3F87D]
	(No symbol) [0x00007FF652D2ED49]
	BaseThreadInitThunk [0x00007FFC121D259D+29]
	RtlUserThreadStart [0x00007FFC13EAAF38+40]

2024-12-25 20:26:49 - Logger - ERROR: Traceback (most recent call last):
  File "d:\test-rpa\utils\custom_utils.py", line 76, in find_elements
    elements = WebDriverWait(driver, EXPLICIT_WAIT).until(
        EC.presence_of_all_elements_located(locator)
    )
  File "C:\Users\kasun\AppData\Local\Programs\Python\Python313\Lib\site-packages\selenium\webdriver\support\wait.py", line 96, in until
    value = method(self._driver)
  File "C:\Users\kasun\AppData\Local\Programs\Python\Python313\Lib\site-packages\selenium\webdriver\support\expected_conditions.py", line 191, in _predicate
    return driver.find_elements(*locator)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
  File "C:\Users\kasun\AppData\Local\Programs\Python\Python313\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 792, in find_elements
    return self.execute(Command.FIND_ELEMENTS, {"using": by, "value": value})["value"] or []
           ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kasun\AppData\Local\Programs\Python\Python313\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 384, in execute
    self.error_handler.check_response(response)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
  File "C:\Users\kasun\AppData\Local\Programs\Python\Python313\Lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 232, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.InvalidArgumentException: Message: invalid argument: 'using' must be a string
  (Session info: chrome=131.0.6778.205)
Stacktrace:
	GetHandleVerifier [0x00007FF652DCFB05+28789]
	(No symbol) [0x00007FF652D386E0]
	(No symbol) [0x00007FF652BD592A]
	(No symbol) [0x00007FF652C290C5]
	(No symbol) [0x00007FF652C295FC]
	(No symbol) [0x00007FF652C728D7]
	(No symbol) [0x00007FF652C4F47F]
	(No symbol) [0x00007FF652C6F654]
	(No symbol) [0x00007FF652C4F1E3]
	(No symbol) [0x00007FF652C1A938]
	(No symbol) [0x00007FF652C1BAA1]
	GetHandleVerifier [0x00007FF65310933D+3410093]
	GetHandleVerifier [0x00007FF65311E7DD+3497293]
	GetHandleVerifier [0x00007FF653112A73+3448803]
	GetHandleVerifier [0x00007FF652E97BBB+848171]
	(No symbol) [0x00007FF652D43C3F]
	(No symbol) [0x00007FF652D3F6E4]
	(No symbol) [0x00007FF652D3F87D]
	(No symbol) [0x00007FF652D2ED49]
	BaseThreadInitThunk [0x00007FFC121D259D+29]
	RtlUserThreadStart [0x00007FFC13EAAF38+40]


2024-12-25 20:26:49 - Logger - ERROR: 예상치 못한 예외 발생: InvalidArgumentException
2024-12-25 20:26:49 - Logger - INFO: 스크린샷 저장 완료: d:\test-rpa\screenshots\NoneType_기기추천탭(('cssselector','div.device-section'),'.tab-wrapulli')들을찾지못했습니다._20241225202649.png
2024-12-25 20:26:49 - Logger - INFO: 기기 추천 탭: []
2024-12-25 20:26:49 - Logger - INFO: ===================================테스트 케이스 실행 완료: TestCase03===================================
2024-12-25 20:27:27 - Logger - INFO: ===================================테스트 케이스 실행 시작: TestCase03===================================
2024-12-25 20:27:27 - Logger - INFO: 기기 추천 영역('css selector', 'div.device-section')(을)를 찾았습니다.
2024-12-25 20:27:29 - Logger - INFO: 기기 추천 영역<selenium.webdriver.remote.webelement.WebElement (session="5289e2b8f5bd9a0200bdce5526f93c91", element="f.BA0084CB904DF8887753A87DEFEA8A68.d.C6FF154569107F30C401189DC5A477DF.e.2804")>로 마우스를 이동했습니다.
2024-12-25 20:27:29 - Logger - INFO: 기기 추천 탭('css selector', 'div.device-section .tab-wrap ul li')들을 3개 찾았습니다.
2024-12-25 20:27:29 - Logger - INFO: 기기 추천 탭: [<selenium.webdriver.remote.webelement.WebElement (session="5289e2b8f5bd9a0200bdce5526f93c91", element="f.BA0084CB904DF8887753A87DEFEA8A68.d.C6FF154569107F30C401189DC5A477DF.e.2560")>, <selenium.webdriver.remote.webelement.WebElement (session="5289e2b8f5bd9a0200bdce5526f93c91", element="f.BA0084CB904DF8887753A87DEFEA8A68.d.C6FF154569107F30C401189DC5A477DF.e.2562")>, <selenium.webdriver.remote.webelement.WebElement (session="5289e2b8f5bd9a0200bdce5526f93c91", element="f.BA0084CB904DF8887753A87DEFEA8A68.d.C6FF154569107F30C401189DC5A477DF.e.2564")>]
2024-12-25 20:27:29 - Logger - INFO: ===================================테스트 케이스 실행 완료: TestCase03===================================
2024-12-25 20:30:03 - Logger - INFO: ===================================테스트 케이스 실행 시작: TestCase03===================================
2024-12-25 20:30:04 - Logger - INFO: 기기 추천 영역('css selector', 'div.device-section')(을)를 찾았습니다.
2024-12-25 20:30:05 - Logger - INFO: 기기 추천 영역<selenium.webdriver.remote.webelement.WebElement (session="4f0a13d50aae89273c288da9db6f6154", element="f.4A855B75B2672EB56061D22820AFC0BC.d.35A64174F93E9CEF3836F4F1FB34A98E.e.2607")>로 마우스를 이동했습니다.
2024-12-25 20:30:05 - Logger - INFO: ===================================테스트 케이스 실행 완료: TestCase03===================================
2024-12-25 20:30:20 - Logger - INFO: ===================================테스트 케이스 실행 시작: TestCase03===================================
2024-12-25 20:30:20 - Logger - INFO: 기기 추천 영역('css selector', 'div.device-section')(을)를 찾았습니다.
2024-12-25 20:30:21 - Logger - INFO: 기기 추천 영역<selenium.webdriver.remote.webelement.WebElement (session="20031ccf1f788911dd1ba08f93062fa1", element="f.EA3AE182C1F81C675AAEFAAC00D9F961.d.BB00F7283E08BFF7F21370E669D94C3E.e.2325")>로 마우스를 이동했습니다.
2024-12-25 20:30:21 - Logger - INFO: ===================================테스트 케이스 실행 완료: TestCase03===================================
2024-12-25 20:31:16 - Logger - INFO: ===================================테스트 케이스 실행 시작: TestCase03===================================
2024-12-25 20:31:16 - Logger - INFO: 기기 추천 영역('css selector', 'div.device-section .tab-wrap ul li')들을 3개 찾았습니다.
2024-12-25 20:31:16 - Logger - INFO: 기기 추천 탭: [<selenium.webdriver.remote.webelement.WebElement (session="dfb207da7d213381e20cfeadb78c1637", element="f.3F2C3686D1C6C49AA398DA55C4E4E22C.d.FAAEEB05BFEFE7F4567EBFB9FB632CA8.e.2402")>, <selenium.webdriver.remote.webelement.WebElement (session="dfb207da7d213381e20cfeadb78c1637", element="f.3F2C3686D1C6C49AA398DA55C4E4E22C.d.FAAEEB05BFEFE7F4567EBFB9FB632CA8.e.2404")>, <selenium.webdriver.remote.webelement.WebElement (session="dfb207da7d213381e20cfeadb78c1637", element="f.3F2C3686D1C6C49AA398DA55C4E4E22C.d.FAAEEB05BFEFE7F4567EBFB9FB632CA8.e.2406")>]
2024-12-25 20:31:16 - Logger - INFO: ===================================테스트 케이스 실행 완료: TestCase03===================================
2024-12-25 20:31:35 - Logger - INFO: ===================================테스트 케이스 실행 시작: TestCase03===================================
2024-12-25 20:31:35 - Logger - INFO: 기기 추천 탭('css selector', 'div.device-section .tab-wrap ul li')들을 3개 찾았습니다.
2024-12-25 20:31:35 - Logger - INFO: 기기 추천 탭: [<selenium.webdriver.remote.webelement.WebElement (session="c5db92ee073228c42fc24af793e2822d", element="f.2F538D7AD685E8B7E2393230C803CC3F.d.1B0BC6845E474C165FB7C007A162C032.e.2203")>, <selenium.webdriver.remote.webelement.WebElement (session="c5db92ee073228c42fc24af793e2822d", element="f.2F538D7AD685E8B7E2393230C803CC3F.d.1B0BC6845E474C165FB7C007A162C032.e.2205")>, <selenium.webdriver.remote.webelement.WebElement (session="c5db92ee073228c42fc24af793e2822d", element="f.2F538D7AD685E8B7E2393230C803CC3F.d.1B0BC6845E474C165FB7C007A162C032.e.2207")>]
2024-12-25 20:31:35 - Logger - INFO: ===================================테스트 케이스 실행 완료: TestCase03===================================
2024-12-25 20:39:33 - Logger - INFO: ===================================테스트 케이스 실행 시작: TestCase03===================================
2024-12-25 20:39:33 - Logger - INFO: 기기 추천 영역('css selector', 'div.device-section .tab-wrap ul li')들을 3개 찾았습니다.
2024-12-25 20:39:33 - Logger - INFO: 기기 추천 탭: [<selenium.webdriver.remote.webelement.WebElement (session="ca4723f273806243293e0ae0ba98f4ea", element="f.0E5C94C9C7F18E82396235B46FAA3F71.d.6D51A01A4494EDC304DE83889CD731B6.e.2522")>, <selenium.webdriver.remote.webelement.WebElement (session="ca4723f273806243293e0ae0ba98f4ea", element="f.0E5C94C9C7F18E82396235B46FAA3F71.d.6D51A01A4494EDC304DE83889CD731B6.e.2524")>, <selenium.webdriver.remote.webelement.WebElement (session="ca4723f273806243293e0ae0ba98f4ea", element="f.0E5C94C9C7F18E82396235B46FAA3F71.d.6D51A01A4494EDC304DE83889CD731B6.e.2526")>]
2024-12-25 20:39:33 - Logger - ERROR: 기기 추천 탭[<selenium.webdriver.remote.webelement.WebElement (session="ca4723f273806243293e0ae0ba98f4ea", element="f.0E5C94C9C7F18E82396235B46FAA3F71.d.6D51A01A4494EDC304DE83889CD731B6.e.2522")>, <selenium.webdriver.remote.webelement.WebElement (session="ca4723f273806243293e0ae0ba98f4ea", element="f.0E5C94C9C7F18E82396235B46FAA3F71.d.6D51A01A4494EDC304DE83889CD731B6.e.2524")>, <selenium.webdriver.remote.webelement.WebElement (session="ca4723f273806243293e0ae0ba98f4ea", element="f.0E5C94C9C7F18E82396235B46FAA3F71.d.6D51A01A4494EDC304DE83889CD731B6.e.2526")>]들을 찾지못했습니다.: WebDriver.find_elements() takes from 1 to 3 positional arguments but 4 were given
2024-12-25 20:39:33 - Logger - ERROR: Traceback (most recent call last):
  File "d:\test-rpa\utils\custom_utils.py", line 76, in find_elements
    elements = WebDriverWait(driver, EXPLICIT_WAIT).until(
        EC.presence_of_all_elements_located(locator)
    )
  File "C:\Users\kasun\AppData\Local\Programs\Python\Python313\Lib\site-packages\selenium\webdriver\support\wait.py", line 96, in until
    value = method(self._driver)
  File "C:\Users\kasun\AppData\Local\Programs\Python\Python313\Lib\site-packages\selenium\webdriver\support\expected_conditions.py", line 191, in _predicate
    return driver.find_elements(*locator)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
TypeError: WebDriver.find_elements() takes from 1 to 3 positional arguments but 4 were given

2024-12-25 20:39:33 - Logger - ERROR: 예상치 못한 예외 발생: TypeError
2024-12-25 20:39:33 - Logger - INFO: 스크린샷 저장 완료: d:\test-rpa\screenshots\NoneType_기기추천탭[<selenium.webdriver.remote.webelement.WebElement(session="ca4723f273806243293e0ae0ba98f4ea",element="f.0E5C94C9C7F18E82396235B46FAA3F71.d.6D51A01A4494EDC304DE83889CD731B6.e.2522")>,<selenium.webdriver.remote.webelement.WebElement(session="ca4723f273806243293e0ae0ba98f4ea",element="f.0E5C94C9C7F18E82396235B46FAA3F71.d.6D51A01A4494EDC304DE83889CD731B6.e.2524")>,<selenium.webdriver.remote.webelement.WebElement(session="ca4723f273806243293e0ae0ba98f4ea",element="f.0E5C94C9C7F18E82396235B46FAA3F71.d.6D51A01A4494EDC304DE83889CD731B6.e.2526")>]들을찾지못했습니다._20241225203933.png
2024-12-25 20:39:33 - Logger - INFO: ===================================테스트 케이스 실행 완료: TestCase03===================================
2024-12-25 20:40:11 - Logger - INFO: ===================================테스트 케이스 실행 시작: TestCase03===================================
2024-12-25 20:40:11 - Logger - INFO: 기기 추천 영역('css selector', 'div.device-section .tab-wrap ul li')들을 3개 찾았습니다.
2024-12-25 20:40:11 - Logger - INFO: 기기 추천 탭: [<selenium.webdriver.remote.webelement.WebElement (session="ba4d6f1170ff91d4e51765c0f36c9ad6", element="f.AA4B0C960FFCAA2E950834C12FD193C4.d.4B9C700F254833CEA0B9517E252255DC.e.2115")>, <selenium.webdriver.remote.webelement.WebElement (session="ba4d6f1170ff91d4e51765c0f36c9ad6", element="f.AA4B0C960FFCAA2E950834C12FD193C4.d.4B9C700F254833CEA0B9517E252255DC.e.2117")>, <selenium.webdriver.remote.webelement.WebElement (session="ba4d6f1170ff91d4e51765c0f36c9ad6", element="f.AA4B0C960FFCAA2E950834C12FD193C4.d.4B9C700F254833CEA0B9517E252255DC.e.2119")>]
2024-12-25 20:40:11 - Logger - ERROR: 기기 추천 탭들을 찾지못했습니다.: 'list' object has no attribute 'find_elements'
2024-12-25 20:40:11 - Logger - ERROR: Traceback (most recent call last):
  File "d:\test-rpa\utils\custom_utils.py", line 76, in find_elements
    elements = WebDriverWait(driver, EXPLICIT_WAIT).until(
        EC.presence_of_all_elements_located(locator)
    )
  File "C:\Users\kasun\AppData\Local\Programs\Python\Python313\Lib\site-packages\selenium\webdriver\support\wait.py", line 96, in until
    value = method(self._driver)
  File "C:\Users\kasun\AppData\Local\Programs\Python\Python313\Lib\site-packages\selenium\webdriver\support\expected_conditions.py", line 191, in _predicate
    return driver.find_elements(*locator)
           ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'list' object has no attribute 'find_elements'

2024-12-25 20:40:11 - Logger - ERROR: 예상치 못한 예외 발생: AttributeError
2024-12-25 20:40:11 - Logger - INFO: ===================================테스트 케이스 실행 완료: TestCase03===================================
2024-12-25 20:41:03 - Logger - INFO: ===================================테스트 케이스 실행 시작: TestCase03===================================
2024-12-25 20:41:03 - Logger - INFO: 기기 추천 영역('css selector', 'div.device-section .tab-wrap ul li')들을 3개 찾았습니다.
2024-12-25 20:41:03 - Logger - INFO: 기기 추천 탭: [<selenium.webdriver.remote.webelement.WebElement (session="5e36e2e756f3fad13a2d2442fb67b921", element="f.DE74B870E5D220816FFA2DB9B820944A.d.24153B1484E909A94A776AE4B3F96B7E.e.2407")>, <selenium.webdriver.remote.webelement.WebElement (session="5e36e2e756f3fad13a2d2442fb67b921", element="f.DE74B870E5D220816FFA2DB9B820944A.d.24153B1484E909A94A776AE4B3F96B7E.e.2409")>, <selenium.webdriver.remote.webelement.WebElement (session="5e36e2e756f3fad13a2d2442fb67b921", element="f.DE74B870E5D220816FFA2DB9B820944A.d.24153B1484E909A94A776AE4B3F96B7E.e.2411")>]
2024-12-25 20:41:03 - Logger - ERROR: 기기 추천 영역 테스트 실패: select_random_list_one() takes from 2 to 3 positional arguments but 5 were given
2024-12-25 20:41:03 - Logger - ERROR: Traceback (most recent call last):
  File "d:\test-rpa\pages\main.py", line 48, in execute
    select_random_list_one(self.driver, *device_tabs, f"기기 추천 탭")
    ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: select_random_list_one() takes from 2 to 3 positional arguments but 5 were given

2024-12-25 20:41:03 - Logger - ERROR: 예상치 못한 예외 발생: TypeError
2024-12-25 20:41:03 - Logger - INFO: 스크린샷 저장 완료: d:\test-rpa\screenshots\TestCase03_기기추천영역테스트실패_20241225204103.png
2024-12-25 20:41:03 - Logger - ERROR: ===================================테스트 케이스 실행 실패: TestCase03 - select_random_list_one() takes from 2 to 3 positional arguments but 5 were given===================================
2024-12-25 20:42:17 - Logger - INFO: ===================================테스트 케이스 실행 시작: TestCase03===================================
2024-12-25 20:42:17 - Logger - INFO: 기기 추천 영역('css selector', 'div.device-section .tab-wrap ul li')들을 3개 찾았습니다.
2024-12-25 20:42:17 - Logger - INFO: 기기 추천 탭: [<selenium.webdriver.remote.webelement.WebElement (session="cc497d5ae2dbdcb119de052850cb5543", element="f.A7DBF094FEDD27366B381424A8CAF150.d.D7FB3A3EAA5FEF785112F576C14EB6BD.e.2341")>, <selenium.webdriver.remote.webelement.WebElement (session="cc497d5ae2dbdcb119de052850cb5543", element="f.A7DBF094FEDD27366B381424A8CAF150.d.D7FB3A3EAA5FEF785112F576C14EB6BD.e.2343")>, <selenium.webdriver.remote.webelement.WebElement (session="cc497d5ae2dbdcb119de052850cb5543", element="f.A7DBF094FEDD27366B381424A8CAF150.d.D7FB3A3EAA5FEF785112F576C14EB6BD.e.2345")>]
2024-12-25 20:42:17 - Logger - ERROR: 기기 추천 탭[<selenium.webdriver.remote.webelement.WebElement (session="cc497d5ae2dbdcb119de052850cb5543", element="f.A7DBF094FEDD27366B381424A8CAF150.d.D7FB3A3EAA5FEF785112F576C14EB6BD.e.2341")>, <selenium.webdriver.remote.webelement.WebElement (session="cc497d5ae2dbdcb119de052850cb5543", element="f.A7DBF094FEDD27366B381424A8CAF150.d.D7FB3A3EAA5FEF785112F576C14EB6BD.e.2343")>, <selenium.webdriver.remote.webelement.WebElement (session="cc497d5ae2dbdcb119de052850cb5543", element="f.A7DBF094FEDD27366B381424A8CAF150.d.D7FB3A3EAA5FEF785112F576C14EB6BD.e.2345")>]들을 찾지못했습니다.: WebDriver.find_elements() takes from 1 to 3 positional arguments but 4 were given
2024-12-25 20:42:17 - Logger - ERROR: Traceback (most recent call last):
  File "d:\test-rpa\utils\custom_utils.py", line 76, in find_elements
    elements = WebDriverWait(driver, EXPLICIT_WAIT).until(
        EC.presence_of_all_elements_located(locator)
    )
  File "C:\Users\kasun\AppData\Local\Programs\Python\Python313\Lib\site-packages\selenium\webdriver\support\wait.py", line 96, in until
    value = method(self._driver)
  File "C:\Users\kasun\AppData\Local\Programs\Python\Python313\Lib\site-packages\selenium\webdriver\support\expected_conditions.py", line 191, in _predicate
    return driver.find_elements(*locator)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
TypeError: WebDriver.find_elements() takes from 1 to 3 positional arguments but 4 were given

2024-12-25 20:42:17 - Logger - ERROR: 예상치 못한 예외 발생: TypeError
2024-12-25 20:42:17 - Logger - INFO: 스크린샷 저장 완료: d:\test-rpa\screenshots\NoneType_기기추천탭[<selenium.webdriver.remote.webelement.WebElement(session="cc497d5ae2dbdcb119de052850cb5543",element="f.A7DBF094FEDD27366B381424A8CAF150.d.D7FB3A3EAA5FEF785112F576C14EB6BD.e.2341")>,<selenium.webdriver.remote.webelement.WebElement(session="cc497d5ae2dbdcb119de052850cb5543",element="f.A7DBF094FEDD27366B381424A8CAF150.d.D7FB3A3EAA5FEF785112F576C14EB6BD.e.2343")>,<selenium.webdriver.remote.webelement.WebElement(session="cc497d5ae2dbdcb119de052850cb5543",element="f.A7DBF094FEDD27366B381424A8CAF150.d.D7FB3A3EAA5FEF785112F576C14EB6BD.e.2345")>]들을찾지못했습니다._20241225204217.png
2024-12-25 20:42:17 - Logger - INFO: ===================================테스트 케이스 실행 완료: TestCase03===================================
2024-12-25 20:44:26 - Logger - INFO: ===================================테스트 케이스 실행 시작: TestCase03===================================
2024-12-25 20:44:26 - Logger - INFO: 기기 추천 영역('css selector', 'div.device-section .tab-wrap ul li')들을 3개 찾았습니다.
2024-12-25 20:44:26 - Logger - INFO: 기기 추천 탭: [<selenium.webdriver.remote.webelement.WebElement (session="99f24be556292e15df2e1880bbc46c08", element="f.55AA4B6BBB2D161C486650AAF5C01444.d.D2819FF47AA603D1AAB9500871EA022B.e.2039")>, <selenium.webdriver.remote.webelement.WebElement (session="99f24be556292e15df2e1880bbc46c08", element="f.55AA4B6BBB2D161C486650AAF5C01444.d.D2819FF47AA603D1AAB9500871EA022B.e.2041")>, <selenium.webdriver.remote.webelement.WebElement (session="99f24be556292e15df2e1880bbc46c08", element="f.55AA4B6BBB2D161C486650AAF5C01444.d.D2819FF47AA603D1AAB9500871EA022B.e.2043")>]
2024-12-25 20:44:26 - Logger - INFO: 기기 추천 탭('css selector', 'div.device-section .tab-wrap ul li')들을 3개 찾았습니다.
2024-12-25 20:44:26 - Logger - INFO: 기기 추천 탭(을)를 랜덤하게 요소 선택: ('css selector', 'div.device-section .tab-wrap ul li')
2024-12-25 20:44:26 - Logger - INFO: ===================================테스트 케이스 실행 완료: TestCase03===================================
2024-12-25 20:53:52 - Logger - INFO: ===================================테스트 케이스 실행 시작: TestCase03===================================
2024-12-25 20:53:52 - Logger - INFO: 기기 추천 영역('css selector', 'div.device-section')(을)를 찾았습니다.
2024-12-25 20:53:53 - Logger - INFO: 기기 추천 영역<selenium.webdriver.remote.webelement.WebElement (session="aae35417f512bdff64aa4c4c48e7df38", element="f.048398516BD497CE634E60A773A6FAFA.d.5E01B8B8BDB97437856BEB5B14FD6DE6.e.2945")>로 마우스를 이동했습니다.
2024-12-25 20:53:53 - Logger - INFO: 기기 추천 탭('css selector', 'div.device-section .tab-wrap ul li a')들을 3개 찾았습니다.
2024-12-25 20:53:53 - Logger - INFO: 기기 추천 탭('css selector', 'div.device-section .tab-wrap ul li')들을 3개 찾았습니다.
2024-12-25 20:53:53 - Logger - INFO: 기기 추천 탭('css selector', 'div.device-section .tab-wrap ul li')(을)를 랜덤하게 선택하였습니다.
2024-12-25 20:53:53 - Logger - INFO: ===================================테스트 케이스 실행 완료: TestCase03===================================
2024-12-25 21:00:31 - Logger - INFO: ===================================테스트 케이스 실행 시작: TestCase03===================================
2024-12-25 21:00:31 - Logger - INFO: 기기 추천 영역('css selector', 'div.device-section')(을)를 찾았습니다.
2024-12-25 21:00:32 - Logger - INFO: 기기 추천 영역<selenium.webdriver.remote.webelement.WebElement (session="8969e13141f6e79fa949fffa345a576f", element="f.9DAE1B50E027F6FEDDD7306F637BB60C.d.4C00CA6128DE5BF742D3620B055D90BB.e.2260")>로 마우스를 이동했습니다.
2024-12-25 21:00:32 - Logger - INFO: 기기 추천 탭('css selector', 'div.device-section .tab-wrap ul li a')들을 3개 찾았습니다.
2024-12-25 21:00:32 - Logger - INFO: 기기 추천 탭('css selector', 'div.device-section .tab-wrap ul li a')들을 3개 찾았습니다.
2024-12-25 21:00:32 - Logger - ERROR: 기기 추천 탭<selenium.webdriver.remote.webelement.WebElement (session="8969e13141f6e79fa949fffa345a576f", element="f.9DAE1B50E027F6FEDDD7306F637BB60C.d.4C00CA6128DE5BF742D3620B055D90BB.e.2017")>(을)를 찾지못했습니다.: selenium.webdriver.remote.webdriver.WebDriver.find_element() argument after * must be an iterable, not WebElement
2024-12-25 21:00:32 - Logger - ERROR: Traceback (most recent call last):
  File "d:\test-rpa\utils\custom_utils.py", line 66, in find_element
    element = WebDriverWait(driver, EXPLICIT_WAIT).until(
        EC.presence_of_element_located(locator)
    )
  File "C:\Users\kasun\AppData\Local\Programs\Python\Python313\Lib\site-packages\selenium\webdriver\support\wait.py", line 96, in until
    value = method(self._driver)
  File "C:\Users\kasun\AppData\Local\Programs\Python\Python313\Lib\site-packages\selenium\webdriver\support\expected_conditions.py", line 84, in _predicate
    return driver.find_element(*locator)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
TypeError: selenium.webdriver.remote.webdriver.WebDriver.find_element() argument after * must be an iterable, not WebElement

2024-12-25 21:00:32 - Logger - ERROR: 예상치 못한 예외 발생: TypeError
2024-12-25 21:00:32 - Logger - INFO: 스크린샷 저장 완료: d:\test-rpa\screenshots\NoneType_기기추천탭<selenium.webdriver.remote.webelement.WebElement(session="8969e13141f6e79fa949fffa345a576f",element="f.9DAE1B50E027F6FEDDD7306F637BB60C.d.4C00CA6128DE5BF742D3620B055D90BB.e.2017")>(을)를찾지못했습니다._20241225210032.png
2024-12-25 21:00:32 - Logger - ERROR: 기기 추천 탭<selenium.webdriver.remote.webelement.WebElement (session="8969e13141f6e79fa949fffa345a576f", element="f.9DAE1B50E027F6FEDDD7306F637BB60C.d.4C00CA6128DE5BF742D3620B055D90BB.e.2019")>(을)를 찾지못했습니다.: selenium.webdriver.remote.webdriver.WebDriver.find_element() argument after * must be an iterable, not WebElement
2024-12-25 21:00:32 - Logger - ERROR: Traceback (most recent call last):
  File "d:\test-rpa\utils\custom_utils.py", line 66, in find_element
    element = WebDriverWait(driver, EXPLICIT_WAIT).until(
        EC.presence_of_element_located(locator)
    )
  File "C:\Users\kasun\AppData\Local\Programs\Python\Python313\Lib\site-packages\selenium\webdriver\support\wait.py", line 96, in until
    value = method(self._driver)
  File "C:\Users\kasun\AppData\Local\Programs\Python\Python313\Lib\site-packages\selenium\webdriver\support\expected_conditions.py", line 84, in _predicate
    return driver.find_element(*locator)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
TypeError: selenium.webdriver.remote.webdriver.WebDriver.find_element() argument after * must be an iterable, not WebElement

2024-12-25 21:00:32 - Logger - ERROR: 예상치 못한 예외 발생: TypeError
2024-12-25 21:00:32 - Logger - INFO: 스크린샷 저장 완료: d:\test-rpa\screenshots\NoneType_기기추천탭<selenium.webdriver.remote.webelement.WebElement(session="8969e13141f6e79fa949fffa345a576f",element="f.9DAE1B50E027F6FEDDD7306F637BB60C.d.4C00CA6128DE5BF742D3620B055D90BB.e.2019")>(을)를찾지못했습니다._20241225210032.png
2024-12-25 21:00:32 - Logger - ERROR: 기기 추천 탭<selenium.webdriver.remote.webelement.WebElement (session="8969e13141f6e79fa949fffa345a576f", element="f.9DAE1B50E027F6FEDDD7306F637BB60C.d.4C00CA6128DE5BF742D3620B055D90BB.e.2021")>(을)를 찾지못했습니다.: selenium.webdriver.remote.webdriver.WebDriver.find_element() argument after * must be an iterable, not WebElement
2024-12-25 21:00:32 - Logger - ERROR: Traceback (most recent call last):
  File "d:\test-rpa\utils\custom_utils.py", line 66, in find_element
    element = WebDriverWait(driver, EXPLICIT_WAIT).until(
        EC.presence_of_element_located(locator)
    )
  File "C:\Users\kasun\AppData\Local\Programs\Python\Python313\Lib\site-packages\selenium\webdriver\support\wait.py", line 96, in until
    value = method(self._driver)
  File "C:\Users\kasun\AppData\Local\Programs\Python\Python313\Lib\site-packages\selenium\webdriver\support\expected_conditions.py", line 84, in _predicate
    return driver.find_element(*locator)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
TypeError: selenium.webdriver.remote.webdriver.WebDriver.find_element() argument after * must be an iterable, not WebElement

2024-12-25 21:00:32 - Logger - ERROR: 예상치 못한 예외 발생: TypeError
2024-12-25 21:00:32 - Logger - INFO: 스크린샷 저장 완료: d:\test-rpa\screenshots\NoneType_기기추천탭<selenium.webdriver.remote.webelement.WebElement(session="8969e13141f6e79fa949fffa345a576f",element="f.9DAE1B50E027F6FEDDD7306F637BB60C.d.4C00CA6128DE5BF742D3620B055D90BB.e.2021")>(을)를찾지못했습니다._20241225210032.png
2024-12-25 21:00:32 - Logger - INFO: 기기 추천 탭('css selector', 'div.device-section .tab-wrap ul li a')(을)를 랜덤하게 선택하였습니다.
2024-12-25 21:00:32 - Logger - INFO: ===================================테스트 케이스 실행 완료: TestCase03===================================
2024-12-25 21:06:00 - Logger - INFO: ===================================테스트 케이스 실행 시작: TestCase03===================================
2024-12-25 21:06:00 - Logger - INFO: 기기 추천 영역('css selector', 'div.device-section')(을)를 찾았습니다.
2024-12-25 21:06:01 - Logger - INFO: 기기 추천 영역<selenium.webdriver.remote.webelement.WebElement (session="7977d4137f82267c9aed3ad0208f62a8", element="f.039C7DBE65CCCFDD3CF83D72D998D914.d.CB7A133816530A145087179F78E8BC7E.e.2614")>로 마우스를 이동했습니다.
2024-12-25 21:06:01 - Logger - INFO: 기기 추천 탭('css selector', 'div.device-section .tab-wrap ul li a')들을 3개 찾았습니다.
2024-12-25 21:06:01 - Logger - INFO: ===================================테스트 케이스 실행 완료: TestCase03===================================
